### ISSUE TITLE
Demo Error https://demo.invoiceplane.com/

### ISSUE THREAD

**Issue by sharklatan** [InvoicePlane/InvoicePlane#1001]
## Expected Behavior

See the demo

## Current Behavior
`An Error Was Encountered

Unable to load the requested language file: language/Australian-English/ip_lang.php `

## Screenshots
![IMG_0744](https://github.com/InvoicePlane/InvoicePlane/assets/5210221/567c88ff-fdc2-4abe-9378-8858778e38a7)

## Steps to Reproduce

1. Naviate to https://demo.invoiceplane.com/

## Context (Environment)

Using Chome Browser .

**Comment by naui95** [comment]
Hi @sharklatan thank you for the report. The issue has been fixed. Have a nice day!
