### ISSUE TITLE
Stripe payments erroring because of invalid content-type

### ISSUE THREAD

**Issue by jdanna** [InvoicePlane/InvoicePlane#1006]
## Expected Behavior
After adding stripe as a provider, attempting to pay an invoice results in an content-type error from stripe.
## Screenshots
![IMG_3670](https://github.com/InvoicePlane/InvoicePlane/assets/25439364/fa0cd9a9-cd39-451a-89fa-2b47ebf476fc)
![IMG_3671](https://github.com/InvoicePlane/InvoicePlane/assets/25439364/ae0c5f67-fe9a-4c7c-b92f-8e5b3b4119b5)
![IMG_3672](https://github.com/InvoicePlane/InvoicePlane/assets/25439364/d42cdc77-2172-4509-b2b8-3a80c39c06fa)

Stripe shows errors happened, but doesn’t provide any more detailed logs

## Possible Solution

Looks like its related to how omnipay is making the request:

https://stackoverflow.com/questions/66241686/laravel-omnipay-stripe-unable-to-send-request-on-linux/66290005#66290005

I tried modifying the payment handler php to add the headers, but it didn’t work

## Steps to Reproduce
-Enable online payments
-Enter stripe keys and enable stripe (i tested with both test mode and live mode keys in stripe - both had the same issue)
-Send an invoice
-Try to pay the invoice with a credit card

**Comment by nielsdrost7** [comment]
@jdanna great news! A pull-request is on its way to resolve this issue.
Once it's done we'll let you know

**Comment by naui95** [comment]
@jdanna are you available to test the new feature? We set up a new payment interface that supports Stripe (and PayPal). We would be grateful if you could do some testing.

**Comment by idressos** [comment]
Experiencing the exact same issue with InvoicePlane v1.6.1 - PHP8.1-FPM - Debian 12.

**Comment by nielsdrost7** [comment]
@idressos see the solution in this branch:
https://github.com/InvoicePlane/InvoicePlane/pull/1046
Are you available to test the branch?

**Comment by idressos** [comment]
> @idressos see the solution in this branch: #1046 Are you available to test the branch?

Yes, I'm available. Please provide any further instructions if necessary except for cloning and deploying.

**Comment by nielsdrost7** [comment]
I _think_ these would be the steps:

-Enable online payments
-Enter stripe keys and enable stripe
-Send an invoice
-Try to pay the invoice with a credit card

**Comment by idressos** [comment]
> I _think_ these would be the steps:
> 
> -Enable online payments -Enter stripe keys and enable stripe -Send an invoice -Try to pay the invoice with a credit card

Haha yes of course. I meant regarding deployment of the branch.
I ran `composer install` and followed the installation guide for 1.6. The webapp is almost completely functional but there is no styling/graphics/CSS?
I managed to get through the installer though.

**Comment by nielsdrost7** [comment]
> The webapp is almost completely functional but there is no styling/graphics/CSS

Would you mind doing:
- `yarn install` and then:
- `yarn grunt` (from the top of my head), it will compile all the styles and .js files for you

**Comment by idressos** [comment]
Hello (after some time),

We have deployed the branch but just today Stripe started asking for further verification 🫠
Will update you very soon once tested.

**Comment by nielsdrost7** [comment]
> but just today Stripe started asking for further verification
Ok, keep us posted.
We're on Discord if you have any questions: https://discord.gg/PPzD2hTrXt

**Comment by idressos** [comment]
> > but just today Stripe started asking for further verification
> 
> Ok, keep us posted. We're on Discord if you have any questions: https://discord.gg/PPzD2hTrXt

Branch successfully tested and works. 
I actually went all the way through without test mode and the payment was processed.
Payment was registered in the system and invoice balance was zeroed correctly.
From my point of view, everything works as it should.

p.s. I'd like to see the option to pay a custom amount with card in the future, but that's for another ticket.

**Comment by nielsdrost7** [comment]
@idressos thank you very much for testing it.
I'll put it on my "ready to merge" list.

Should be in version 1.6.2 once we start preparing that release
