### ISSUE TITLE
Add php-dom and php-xml to prerequisites (and the Docker image Dockerfile)

### ISSUE THREAD

**Issue by nielsdrost7** [InvoicePlane/InvoicePlane#1010]
## Current Behavior
From the [forum](https://community.invoiceplane.com/t/topic/10357):
> Installed invoiceplane for a friend ran into a problem that through the customer porthole when viewing the invoice if you want to download the pdf you get an error I needed to install php81-xml and php81-dom to get this to work once again don’t know if all distros are the same but maybe should be noted in the requirement section on the Wiki

## Possible Implementation
```
RUN install-php-extensions \
    bcmath \
    exif \
    gd \
    imagick \
    imap \
dom \ <<<====
xml \ <<<===
    intl \
    mysqli \
    pdo_mysql \
    redis \
    soap \
    xdebug \
    xsl \
    zip
```

And it's not in the `requirements`: `[wiki/en/1_6/getting_started/requirements.blade.php](https://github.com/InvoicePlane/Wiki/blob/master/wiki/en/1_6/getting_started/requirements.blade.php)`

**Comment by naui95** [comment]
@nielsdrost7 `wiki` was updated. I'll leave the issue open for `Docker`
