### ISSUE TITLE
Web invoice does not show logo

### ISSUE THREAD

**Issue by jmclaren7** [InvoicePlane/InvoicePlane#1012]
## Expected Behavior
The invoice's web view uses invoice_logo() in invoice_helper.php, this function should provide a URL to the IP configured logo

## Current Behavior
invoice_logo() produces an invalid URL based on an absolute file system path, it seems this change was only intended for invoice_logo_pdf()

## Possible Solution
#1013

**Comment by nielsdrost7** [comment]
Thanks for the bug report, man!
Can you help me out with an example of this one:
- The invoice's web view uses invoice_logo() in invoice_helper.php
And basically this one as well:
- invoice_logo() produces an invalid URL based on an absolute file system path

I'm looking to reproduce the problem and then of course merge your fix.

What I want to prevent is that after merging some other logo's won't show again, if you know what I mean.

**Comment by jmclaren7** [comment]
Just to restate the issue: when viewing an invoice using the web view, the logo will not load. When viewing what URL was generated from the template we can see that it's a file system path, in my case:

![image](https://github.com/InvoicePlane/InvoicePlane/assets/3019173/c6ece5e6-2a10-48a6-8ffe-08f980fef36a)


In #898 / #964 the stated issue was related to PDF's only but both invoice_logo() invoice_logo_pdf() were modified. As far as I can tell the main difference between the two functions is that:
- invoice_logo_pdf() should return a file system path so mpdf can load the logo for server side pdf generation
- invoice_logo() should return a public URL that can be used by a visitors browser to load the logo

#964 seems to have modified both functions when working on an issue related specifically to PDFs. 

In #897 the issue was related to PDF and only invoice_logo_pdf() was modified so it wont be related to my issue.

You can see in the default PDF template, the logo is pulled with invoice_logo_pdf() so as long as that function isn't modified those referenced issues/pulls should not be impacted unless someone used invoice_logo() in a custom pdf template by mistake. https://github.com/InvoicePlane/InvoicePlane/blob/cfc713f89335d2a247c6f1153da38e27bfe78638/application/views/invoice_templates/pdf/InvoicePlane.php#L14

The change I just added was because I made a mistake and had an extra slash because i didn't see that base_url() includes a trailing slash.
