### ISSUE TITLE
CSS File Missing in the Repository

### ISSUE THREAD

**Issue by varactor** [InvoicePlane/InvoicePlane#1015]
## Expected Behavior

After git clone the project has no css file in /assets/invoiceplane/css/style.css
## Current Behavior

The app loads without stylesheet
## Possible Solution

How can we pull the assets as well?
## Steps to Reproduce

1. git clone the project
2. install (you will already notice there's no stylesheet
3. after first login, the app looks totally without style
4. view source and if you click on the style sheet link it gives 404

## Context (Environment)

NA

NA
## Detailed Description

NA
## Possible Implementation

Some instructions how to pull the assets

**Comment by nielsdrost7** [comment]
Next time, please post this on the forums: community.invoiceplane.com

This is not a bug.

After git clone of our project you need to do 2 things:
- install the composer packages:
`composer install`
- install the npm packages and then `compile` the css and js files`
`yarn install && yarn grunt`

This is thr reason why there's a prepared .zip file in the `releases` section on github, so you won't have to take those steps
