### ISSUE TITLE
custom fields array isn't ordered based on Order field

### ISSUE THREAD

**Issue by wendelinux** [InvoicePlane/InvoicePlane#1018]
when adding following code

<?php 
foreach ($custom_fields['user'] as $x => $y) {
		if ($y) {echo "$x : $y <br>";}
}?>

in my template, the result is spit out as it is found in database.

## Expected Behavior

the array should be ordered based on Order set in settings => Custom fields

## Current Behavior

array isn't ordered

## Screenshots

see below screenshot from my setting
![image](https://github.com/InvoicePlane/InvoicePlane/assets/137876976/321d76e2-53bc-4fa2-8da2-d1e175f7fc85)

and below what my code spits out
![image](https://github.com/InvoicePlane/InvoicePlane/assets/137876976/8b33b09a-d451-4df6-b85a-7e88b4da7230)

in settings i put dic in position 0 and ico in position 1

my code loops all elements and it results with ico on position 0 and dic in position 1

## Possible Solution
when building the query it can be added "order by Order ASC"

**Comment by wendelinux** [comment]
I mixed the client and user array... my bad. issue wasn't even there :)

**Comment by nielsdrost7** [comment]
It's still a greatly filled issue, thank you very much.

Keep'em coming
