### ISSUE TITLE
Creation dates of invoices should never be changed

### ISSUE THREAD

**Issue by mheiduk** [InvoicePlane/InvoicePlane#1033]
Based on a conversation in another issue with @Verony-makesIT: https://github.com/InvoicePlane/InvoicePlane/issues/1025#issuecomment-1919883551

Creation dates of invoices should never be changed and this feature first mentioned in https://github.com/InvoicePlane/InvoicePlane/issues/895 should just change the due date. This is highly confusing when the creation date invoices are changing, especially when they are created eg. in 2023 and a reminder will be sent out in 2024.

I know that you can disable it, but 1) this is the default behaviour if you setup invoiceplane out of the box and 2) it is not legal to do that. The correct way to change an invoice creation date is to cancel the invoice and create a new one.

I can provide a suitable pull request if needed.

**Comment by nielsdrost7** [comment]
Don't worry about the PR for now.
I don't think I've merged that PR, at least, I don't think so 🤔.
You are absolutely right about that invoice date.
If we won't change anything there, we won't have a problem, correct?

**Comment by novafirst** [comment]
Apologies for the interruption. Here are my thoughts:

Invoice Information:
- Invoice Created Date/Time: 09-20-2023 17:14:08
- Invoice Updated Date/Time: 09-21-2023 11:11:34
- Invoice Date: 09-23-2023
- Invoice Due Date: 10-04-2023

Please note that the first two fields, "Invoice Created Date/Time" and "Invoice Updated Date/Time," should be for internal reference only and should not be printed or displayed on the invoice itself. These timestamps should automatically be generated and retained solely for internal auditing purposes.

Regarding the last two fields, "Invoice Date" and "Invoice Due Date," these are the crucial details to be presented on the invoice. The "Invoice Date" should be selectable by the user, ensuring it falls between the current date and the "Invoice Due Date." It's important to consider that payment terms may vary; some invoices may require payment upon receipt, while others may follow specific terms like NET 10, 15, 30, etc.

**Comment by mheiduk** [comment]
@Verony-makesIT I understand your point that when you initially send the invoice to the client, the creation date can be changed to the date when you've sent the invoice. But adjusting the creation date when you send the client a reminder email is confusing and should not happen. You can circumvent this behaviour if the read-only setting is set to "Sent", but when it's set to "Paid" the reminder email will update the creation date nonetheless.

To prevent further confusion when to update the creation date and when not, the creation should not be updated automatically at all in my opinion. If you still want to change the creation date of the invoice, you can do it manually anyway.
