### ISSUE TITLE
Translation breaks in PDF-template

### ISSUE THREAD

**Issue by jmmeijer** [InvoicePlane/InvoicePlane#1034]
## Expected Behavior

Translation should be based on system setting

## Current Behavior

Translation is reverted to English as default

## Possible Solution

In file application/helpers/trans_helper.php
Replace line 37:
`$current_language = 'english';`
with:
`$current_language = get_setting('default_language') ?? 'english';`

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

In a PDF-template for an invoice the first strings will be properly translated, however after one point, (for an unknown reason) it will revert to English. After this, all other string will be English.

**Comment by nielsdrost7** [comment]
Thanks for the Bug Report, man!
Solved in PR https://github.com/InvoicePlane/InvoicePlane/pull/1035
It's now merged into the `develop` branch.

Will be released with version `1.6.2`

**Comment by jmmeijer** [comment]
You're very welcome, It was my intention to provider more details on the cause, but to my surprise it was already merged into dev! You're fast, Niels!

**Comment by nielsdrost7** [comment]
This one:

> however after one point, (for an unknown reason) it will revert to English. After this, all other string will be English

Is an interesting one, let me look up an old issue

**Comment by naui95** [comment]
fix was merged with #1035. Closing the issue for the moment since no other report has been made.
