### ISSUE TITLE
custom field values are not saved or even worse deleted

### ISSUE THREAD

**Issue by gklimm** [InvoicePlane/InvoicePlane#1047]
There are several additional fields defined in the customer.
When saving the customer, existing values are sometimes set to NULL in the database or not saved at all.
After being repeated several times, they are saved at some point, which is very annoying and cannot be communicated to the user.
## Expected Behavior

customer fields should be saved
existing information should not be deleted
## Current Behavior

fields on the customer are sometimes saved
existing information is sometimes deleted (overwritten with NULL)
## Steps to Reproduce

1. Define custom fields
2. Enter Information there
3. Save the customer

**Comment by gklimm** [comment]
I hadn't managed the order of the fields before (all set to zero because I didn't care)
Maybe that's where the problem came from. I'll keep an eye on it for now.
If that is the problem, the software should prevent you from not managing or double managing there

**Comment by gklimm** [comment]
Does anyone have any ideas for a short-term patch? The error is really annoying. We are currently packing all the content again as a note to the customer in case it disappears again 

I don't have a chance to look at the code this week

**Comment by naui95** [comment]
@gklimm what IP version are you using?

**Comment by naui95** [comment]
Dear @gklimm, given that we don't seem to be able to reproduce the error I suggest we close the issue. You can reopen it anytime if the bug should reappear.

**Comment by nielsdrost7** [comment]
> `application/modules/clients/controllers/Clients.php`

Add some logging above this:

```$result = $this->mdl_client_custom->save_custom($id, $this->input->post('custom'));```

And below that ^^^
And what you can do is log the "result", maybe with a "var_dump" if logging can handle that. Maybe the result is `false` or `true` and that in a log is not great info
