### ISSUE TITLE
database structure required

### ISSUE THREAD

**Issue by muhammadasad251** [InvoicePlane/InvoicePlane#1049]
I need database structure please

**Comment by johnfoley** [comment]
Wed 8 May.

Thanks for your mail. I am currently out of the office with limited access to my email. For any time-sensitive matters please do not hesitate to contact me on my mobile, otherwise I will respond to your mail on my return.

**Comment by nielsdrost7** [comment]
So ... we don't have the database structure available for you.
What you can do Is opened up an InvoicePlane database in a tool like MySQL workbench, that will give you all the tables.

Now you can connect those tables in Workbench's tool.

As far as InvoicePlane is concerned, we don't and we won't have database structure available.

**Comment by johnfoley** [comment]
Thu 9 May.

Thanks for your mail. I am currently out of the office with limited access to my email. For any time-sensitive matters please do not hesitate to contact me on my mobile, otherwise I will respond to your mail on my return.
