### ISSUE TITLE
The session times out too frequently and I get logged out

### ISSUE THREAD

**Issue by christoferd** [InvoicePlane/InvoicePlane#1052]
For some reason the app times out too frequently.

I'm a developer and have tried a few things to increase it. Primarily the values in the config for session/cookie.
ipconfig.php
```SESS_EXPIRATION=864000 ```
/application/config/config.php
```$config['cookie_secure'] = env('COOKIE_SECURE', true); ```

Why doesn't that work?

I would like the login to time-out only once per week, or longer, I don't want to keep loggin in.
Frustrating when I leave an invoice open to edit later on (or keep updating as I work), and the app times out :-(

**Comment by nielsdrost7** [comment]
I think you mean that the session times out, which means you get logged out.

The solution is as follows:
Open `ipconfig.php`
Add this: `SESS_SAVE_PATH=`

What you set as the path is for example a directory inside InvoicePlane's directory (I had to create one for belongs solution)

I have mine set to:
`SESS_SAVE_PATH=/var/www/invoiceplane/sessions`

**Comment by nielsdrost7** [comment]
Ok, I'm going to close this issue.
For follow-up questions go to https://community.invoiceplane.com or go to our Discord channel
