### ISSUE TITLE
404 Not Found When Attempting Setup

### ISSUE THREAD

**Issue by hexxamillion** [InvoicePlane/InvoicePlane#1060]
## Expected Behavior

The web setup page should display.

## Current Behavior

I get 404 not found when accessing my URL with http://localhost:[port]/dev/index.php/setup 

## Screenshots

![image](https://github.com/InvoicePlane/InvoicePlane/assets/1843715/b40435b3-70f8-46bd-bea8-2537ef83070b)

## Steps to Reproduce

1. Follow setup steps for updating ipconfig.php
2. Access setup url
3.
4.

## Context (Environment)
 Initial setup

I am running Nginx on Ubuntu 22.04 and PHP 8.3.8

**Comment by nielsdrost7** [comment]
Hey,
Thanks for your report.
PHP 8.3 isn't supported
PHP 8.2 isn't supported

And now for your question:
- open up `ipconfig.php`
- Find `REMOVE_INDEXPHP=false` and change it to `true`
- Reload the page, see if it loads
I don't know about that `/dev` part. It depends on your nginx config file
Same goes for the port, it depends on your nginx config

Here's an example nginx config file:
resources/docker/nginx/invoiceplane.conf

I placed `ivpl.local` in my `/etc/hosts` file so I don't need to do weird things with ports and subdirectories

**Comment by nielsdrost7** [comment]
@hexxamillion I'm going to close this issue.

InvoicePlane was built with CodeIgniter V3 (don't ask).
As long as CodeIgniter V3 isn't compatible with PHP 8.2 and higher, InvoicePlane can't either.
The 404's can be handled in 2 ways:
- Remove /index.php/ from the Url
- Find out what's causing the 404 in your nginx config (see my earlier remarks)

If you have any more questions regarding InvoicePlane with PHP 8.1 you can find me on the community forums https://community.invoiceplane.com or on Slack: https://join.slack.com/t/invoiceplane/shared_invite/zt-2kidwnpkk-yTI7~x9Wi6lE~D0NgMpU6g
