### ISSUE TITLE
Project dashboard widget - broken link when no customer assigned to project

### ISSUE THREAD

**Issue by NiklasSchmitt** [InvoicePlane/InvoicePlane#1072]
## Expected Behavior

When no customer to a project is assigned, hide the link to the customer on the project widget on the dashboard.

## Current Behavior

On project dashboard widget is an broken link to see.

## Screenshots

![grafik](https://github.com/user-attachments/assets/025231d1-732c-45da-a644-6d9342b7fa1f)

## Steps to Reproduce

1. Activate projects-module
2. Create a new project, DO NOT assign a customer
3. Move to dashboard, see in the projects-widget that a not working link to `https://ip.example.com/index.php/clients/view/` is to see.

## Context (Environment)

Using IP 1.6.1

## Possible Implementation

I've checked `application/modules/dashboard/views/index.php` and can apply a pull-request later by mysqlf.

**Comment by nielsdrost7** [comment]
Thanks man! I've merged your PR

**Comment by naui95** [comment]
Closing issue since fix was merged with #1073
