### ISSUE TITLE
Restart of InvoicePlane appends data to the ipconfig.php

### ISSUE THREAD

**Issue by SvenKribitz** [InvoicePlane/InvoicePlane#1076]
## Expected Behavior

The page should load.

## Current Behavior

The page doesn't load, instead there's errors thrown because a connection to the database couldn't be established.

## Screenshots

![image](https://github.com/user-attachments/assets/a05f0496-0093-47b1-997e-51df1ad7a3bc)

## Steps to Reproduce

Installed it on Portainer in a stack:

services:
  invoiceplane:
    hostname: invoiceplane
    image: mhzawadi/invoiceplane:latest
    container_name: invoiceplane
    ports:
      - "3217:80"
    volumes:
      - invoiceplane_data:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_USER=name
      - DB_PASS=pw
      - DB_NAME=invoiceplane
      - IP_URL=http://server.local:3217
      - HOST_URL=server.local:3217

  db:
    hostname: invoiceplane_db
    image: mysql:8.0
    container_name: invoiceplane_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_DATABASE=invoiceplane
      - MYSQL_USER=name
      - MYSQL_PASSWORD=pw

volumes:
  invoiceplane_data:
  db_data:

Restarting the container several times results in the ipconfig.php to look like this:
![image](https://github.com/user-attachments/assets/1b0b5363-4dcc-4920-87f8-0cce4dc6cc4c)
So for some reason it appends the default values.

## Context (Environment)

Workaround after each restart is removing that appendix

**Comment by nielsdrost7** [comment]
@SvenKribitz
Thank you for you issue man, it looks good.

Unfortunately I don't think it's a bug.
Like I said on the forum: try it out with a standard Docker setup. `docker-compose up` and you're done
https://community.invoiceplane.com/t/topic/11249/2
