### ISSUE TITLE
ZUGFeRD Name should not be user name

### ISSUE THREAD

**Issue by pumpi** [InvoicePlane/InvoicePlane#1078]
In the ZUGFeRD XML data the `ram:name` is the username but should be the Company name. For the username you should. use `ram:DefinedTradeContact`

## Expected Behavior

```xml
<ram:Name>Mustermann GmbH</ram:Name>
<ram:DefinedTradeContact>Max Mustermann</ram:DefinedTradeContact>
```

## Current Behavior

```xml
<ram:Name>Max Mustermann</ram:Name>
```

## Possible Solution

add `ram:DefinedTradeContact` if the company in user filled and add the name there and fill `ram:name` with company name

## Steps to Reproduce

https://github.com/InvoicePlane/InvoicePlane/blob/development/application/libraries/ZugferdXml.php#L126

**Comment by nielsdrost7** [comment]
Thanks man!
I'll take a look as soon as I can.
It also means Verony's PR probably needs to be changed.
He gave a zugferd example in one of his PR's

**Comment by pumpi** [comment]
Yeah, I see this PR a check if change this but don't see this, so I open this issue

**Comment by nielsdrost7** [comment]
You did great, I just need to find the time to resolve the problem.
And you gave a solution, which is awesomw

**Comment by gklimm** [comment]
I did the PR myself.
Unfortunately, I'm not as far along as I would have liked because of other projects.
Version 2.3 was released on 18 September. So I will implement that right away (instead of 2.2 as planned).

**Comment by pumpi** [comment]
I can make an PR on the current version with a simple solution if it helps you and Invoice Plane

**Comment by nielsdrost7** [comment]
@pumpi that would be appreciated, thank you.
I've invited you to the InvoicePlane team on github so you can make branches and PR's, etc

And if you want to talk about Zugferd and other things, we're on Discord: https://discord.gg/PPzD2hTrXt

**Comment by pumpi** [comment]
@nielsdrost7 I joined discord. I have done and test my changes. Should I make the branch in bugfix with the ID of the issue?

**Comment by nielsdrost7** [comment]
> Should I make the branch in bugfix with the ID of the issue

Yes please

**Comment by nielsdrost7** [comment]
Thank you for your PR. Looks great.
PR is approved and merged.
