### ISSUE TITLE
Clients invoice tab only shows 20 entries

### ISSUE THREAD

**Issue by pumpi** [InvoicePlane/InvoicePlane#1083]
If you have a client that have a lot of invoices, you can't view all his invoices in the client invoices tab because the client call always has a limit of 20 and no paging (https://github.com/InvoicePlane/InvoicePlane/blob/development/application/modules/clients/controllers/Clients.php#L211). You only can view this at invoices and search for the client name. If you have clients with similar names, this is harder to get.

## Expected Behavior

Show all invoices from clients in the invoices tab

## Current Behavior

Only 20 entries shown and there is no pagination on the result

## Possible Solution

Add a Pagination to the clients tabs to paging the entries, or add a more link that refer to the invoices page with a search by client ID.

## Steps to Reproduce

1. Have a customer with more the 20 invoices
2. Go to a client and open the invoices tab to see only the last 20 entries shown

**Comment by nielsdrost7** [comment]
Great bug report, thank you.
I'm not sure, but if you change `limit(20)` to `paginate()` would that solve your problem?

**Comment by pumpi** [comment]
Yes, I think this is the first step in the right direction, but the next problem is that there is no place for a pagination. It would be easy to refresh the table with Ajax, but the rest of InvoicePLane works with page refreshes, and then we must preselect the invoice tab from the URL to not confuse the user.

**Comment by pumpi** [comment]
I'm working on a first solution. But I think it would be better if the pagination is on the bottom of the Table and not on the top what do you think @nielsdrost7

**Comment by nielsdrost7** [comment]
> But I think it would be better if the pagination is on the bottom of the Table and not on the top

I agree, go with your solution.
And thank you again
