### ISSUE TITLE
Release 1.6.1 yarn.lock and package.json are out of sync

### ISSUE THREAD

**Issue by teutat3s** [InvoicePlane/InvoicePlane#1109]
## Expected Behavior

After running `yarn install`, the `yarn.lock` file should not change.

## Current Behavior

`yarn.lock` gets updated after running `yarn install`.

## Possible Solution
Commit updated `yarn.lock` in a new point release.

## Steps to Reproduce

1. Checkout git repository and switch to latest release tag 1.6.1
```
git clone https://github.com/InvoicePlane/InvoicePlane.git
git checkout v1.6.1
```
3. Run `yarn install`
```
❯ yarn install
yarn install v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 6.71s.
```
5. Run `git diff` or `git status`
```
❯ git status
HEAD detached at v1.6.1
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   yarn.lock
```

## Context (Environment)
When [buillding InvoicePlane from source for nixpkgs](https://github.com/NixOS/nixpkgs/pull/353783), it was noticed that the `package.json` and `yarn.lock` files are currently not in sync. This makes it necessary to vendor the updated `yarn.lock` file in `nixpkgs`, which is not ideal.

**Comment by nielsdrost7** [comment]
Solved by [releasing version 1.6.2](https://github.com/InvoicePlane/InvoicePlane/releases/tag/v1.6.2)
@teutat3s thanks for your issue, man!
This time during building the .zip of version 1.6.2 I've used --frozen-lock-file and i've checked if yarn.lock was changed.

Hope it's ok this time
