### ISSUE TITLE
Directory Traversal Vulnerability & Sensitive File Exposure

### ISSUE THREAD

**Issue by dansecop** [InvoicePlane/InvoicePlane#1126]
Please read SECURITY.md for proper way to report security vulnerability, thank you

**Comment by nielsdrost7** [comment]
Thank you for your vulnerability report.
Please read https://github.com/InvoicePlane/InvoicePlane/blob/development/SECURITY.md for the proper way to report a security vulnerability

**Comment by dansecop** [comment]
Vulnerability report has been shared with mail@invoiceplane.com

**Comment by nielsdrost7** [comment]
I'll archive this issue here, but it will be addressed shortly
