### ISSUE TITLE
Error on input validation (1.6.2 beta)

### ISSUE THREAD

**Issue by xam-ps** [InvoicePlane/InvoicePlane#1130]
1. Go to any input form (e.g. add new tax).
2. Click on save without putting in any values

## Expected Behavior
An input validation should be shown to the user.

## Current Behavior
The application tries to save the values and is running into an error after some time.

## Screenshots
![grafik](https://github.com/user-attachments/assets/73f06f54-d9ff-4ff1-8d95-6aed2bfb2c03)

## Steps to Reproduce
1. Go to any input form (e.g. add new tax).
2. Click on save without putting in any values

## Detailed Description
This happens on any form
- custom_fields form
- email_template form
- invoice_groups/form
- etc.

**Comment by nielsdrost7** [comment]
@sudwebdesign could you take a look at this one as well, please?

**Comment by sudwebdesign** [comment]
Hi, @nielsdrost7 
The fix #1155 by @AeroBytesNL should be fine :+1:.
Note:
Only remove `console.log('ajax-loader');` at line [249](https://github.com/InvoicePlane/InvoicePlane/pull/1155/files#diff-2cb46051b408c1dda73ebd6f22c3ba84076bebdc790ba80630b75d8ca5c790c2R249) to be perfect.

**Comment by AeroBytesNL** [comment]
@sudwebdesign @nielsdrost7 i removed the `console.log()` :)

**Comment by nielsdrost7** [comment]
Solved by #1155 , but I'll keep this one open till after the release

**Comment by nielsdrost7** [comment]
Solved by [releasing version 1.6.2](https://github.com/InvoicePlane/InvoicePlane/releases/tag/v1.6.2)
