### ISSUE TITLE
Lower case language files are breaking 1.6.2 upgrade

### ISSUE THREAD

**Issue by xam-ps** [InvoicePlane/InvoicePlane#1148]
In ip1.6.2 (beta 2) the language files are lowercase. This causes the application to crash, as it is not handled during the migration.

## Expected Behavior
ip1.6.2 (beta 2) should be working after running the migration.

## Current Behavior
Error is shown, as the language file can't be found.

## Screenshots
![grafik](https://github.com/user-attachments/assets/ecc38430-9553-4c46-bdc4-b923af231f0a)

## Possible Solution
Keep the old naming convention for the language file (first letter upper case) or handle it in the migration script.

## Steps to Reproduce
1. Replace ip1.6.1 file with 1.6.2 files
2. Run migration script

**Comment by nielsdrost7** [comment]
Solved by [releasing version 1.6.2](https://github.com/InvoicePlane/InvoicePlane/releases/tag/v1.6.2)
