### ISSUE TITLE
Invoice Archive is broken in 1.6.2

### ISSUE THREAD

**Issue by xam-ps** [InvoicePlane/InvoicePlane#1171]
The Invoice Archive (Settings -> Invoice Archive) is broken in 1.6.2

## Expected Behavior
When I got to "Settings", click on "Invoice Archive" and open an existing pdf, the pdf should be shown/downloaded.

## Current Behavior
After clicking on an invoice, the application gives back a 404.

## Screenshots
![grafik](https://github.com/user-attachments/assets/83cc91a5-934b-43a1-b734-1dfa3f369de3)

## Steps to Reproduce
1. Go to Settings
2. Click on "Invoice Archive"
3. Click on one of the invoices

## Context (Environment)
Old invoices can't be accessed anymore

This bug is already confirmed by @AeroBytesNL

**Comment by AeroBytesNL** [comment]
I'm looking into it as we speak.

**Comment by AeroBytesNL** [comment]
So in the logs you can see it shows: `Invalid file access attempt: 2024-12-30_Invoice_1.pdf.pdf`.
For some reason it tries to add an extra `.pdf`.

I've identified the coding bug. I will create an PR with an couple minutes to fix this. Sad this slipped through testing tho good that you found this bug!

**Comment by xam-ps** [comment]
@AeroBytesNL 
Thank you. Removing the ".pdf" extension did the job for me. Hope this is not having any side effects, but on a first glance it looks solid.
