### ISSUE TITLE
logo quality invoice/quote

### ISSUE THREAD

**Issue by beedesign** [InvoicePlane/InvoicePlane#129]
when I print (PDF) an invoice the quality of the logo is not maximum.(the logo is blurred)
How to set the quality of the logo on the invoice ?
I use as an engine for generating pdf mPDF.
thank you!

**Comment by beedesign** [comment]
thanks , but I put a logo to 300 dpi but the quality does not improve , how can I fix it?
I printed the logo individually on my printer , then I printed invoice with the same logo and is blurred .
thank you.

**Comment by Kovah** [comment]
Ok i'll take a look.

**Comment by MaherSakka** [comment]
I got the same problem so I switched from PNG to SVG format for the logo file.
The logo was rendered like a charm ! Try it !

**Comment by beedesign** [comment]
thanks a lot , I tried but does not allow me to upload the file svg gives me this error :
The filetype you are attempting to upload is not allowed.

**Comment by MaherSakka** [comment]
Actually SVG is not supported !
The easiest way is to harcode the invoice template by replacing:

application/views/invoice_templates/pdf/default.php:

   <?php echo invoice_logo_pdf(); ?>

by 

<img src="/uploads/yourlogo.svg"/>

**Comment by beedesign** [comment]
thank you very much the solution works!
Good luck !

**Comment by MaherSakka** [comment]
@Kovah we have to add svg support when uploading logos

**Comment by nsina** [comment]
+1 for native SVG support
