### ISSUE TITLE
Installed InvoicePlane on CentOs 6.5

### ISSUE THREAD

**Issue by data4voip** [InvoicePlane/InvoicePlane#136]
Hi 
Maybe it should help. Here is a summary of problems I faced during installation. 

1) I unzipped files in a tmp directory, when moving files with mv, .gitignore and .htaccess are not moved.
2) I installed invoiceplane in the sub-directory /invoices/, change this line in .htaccess: RewriteBase /invoices
3) After unzipping and moving files, files are owned by root. chown -R apache:apache /var/www/html/invoices/
4) White page displayed when enterring setup. In the part <Directory "/var/www/html"> of the httpd.conf, change the line  AllowOverride None in AllowOverride All

**Comment by ricUK** [comment]
I am currently running InvoicePlane on CentOS 6.5 VM and therefore I am 100% sure it works. 
Do check CentOS 6.5 apache error logs. If that doesn't help check selinux status

**Comment by lommes** [comment]
I'm not sure but I think this is not a request for support. I think that's just some hints for the case someone runs into issues. Most of the points are not just CentOS related and should work for most Linux.

**Comment by Jadaw1n** [comment]
If that's the case, the wiki is better suited for this. 
I added 4) to the requirements in the wiki.
