### ISSUE TITLE
Recurring invoice

### ISSUE THREAD

**Issue by data4voip** [InvoicePlane/InvoicePlane#137]
I faced a problem.

Recurring email are sent without template.

When I run "curl http://eserver.data4voip.com/invoices/invoices/cron/recur/XXXXXXXXXXXXX" directly from bash, I receive this error...

Invalid address: d

That's all the content of the error message displayed.

I received the message and the invoice is created but without email template.

Is there a solution?

Regards
Baugniet B.

**Comment by data4voip** [comment]
Any news for this poblem?

Regards

**Comment by Kovah** [comment]
No sorry, had no time to check this out. I'll try to take some time tomorrow.

**Comment by AbbyNormal** [comment]
Hi, when I run curl emails which are sent have empty body, they are from root@localhost and pdf is in the attachment. This error is written in terminal after curl.
Invalid address: i<div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  Cannot modify header information - headers already sent by (output started at /home/serverlab/public_html/inv/application/modules/mailer/helpers/phpmailer/class.phpmailer.php:496)</p>
<p>Filename: libraries/Session.php</p>
<p>Line Number: 688</p>

**Comment by Kovah** [comment]
Nothing more? No detailed error message?

**Comment by AbbyNormal** [comment]
Nothing. I even deleted whole installation and went freshly install without any modification. I'm using this on hosting so don't know where to look for the logs. Error log of apache has no entries regarding this...

**Comment by AbbyNormal** [comment]
A bunch of errors in file log-2015-01-26.php inside invoiceplane:
DEBUG - 2015-01-26 21:13:14 --> File loaded: application/views/invoice_templates/pdf/default.php
DEBUG - 2015-01-26 21:13:14 --> Helper loaded: mpdf_helper
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined index: port /home/serverlab/public_html/inv/application/helpers/mpdf/mpdf.php 11427
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined index: port /home/serverlab/public_html/inv/application/helpers/mpdf/mpdf.php 11427
...
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined index: TD>>ID>> /home/serverlab/public_html/inv/application/helpers/mpdf/classes/cssmgr.php 1017
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined index: overflow /home/serverlab/public_html/inv/application/helpers/mpdf/mpdf.php 24040
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined index: headernrows /home/serverlab/public_html/inv/application/helpers/mpdf/mpdf.php 24738
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined index: headernrows /home/serverlab/public_html/inv/application/helpers/mpdf/mpdf.php 24738
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined index: headernrows /home/serverlab/public_html/inv/application/helpers/mpdf
...
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined index: TD>>ID>> /home/serverlab/public_html/inv/application/helpers/mpdf/classes/cssmgr.php 1017
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined index: outline-s /home/serverlab/public_html/inv/application/helpers/mpdf/mpdf.php 4017
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined index: outline-s /home/serverlab/public_html/inv/application/helpers/mpdf/mpdf.php 4017
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined index: outline-s /home/serverlab/public_html/inv/application/helpers/mpdf/mpdf.php 4017
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined index: outline-s /home/serverlab/public_html/inv/application/helpers/mpdf/mpdf.php 4017
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined index: outline-s /home/serverlab/public_html/inv/application/helpers/mpdf/mpdf.php 4017
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined offset: 0 /home/serverlab/public_html/inv/application/helpers/mpdf/mpdf.php 26978
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined index: outline-s /home/serverlab/public_html/inv/application/helpers/mpdf/mpdf.php 4017
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined offset: 1 /h
...
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined index: direction /home/serverlab/public_html/inv/application/helpers/mpdf/mpdf.php 18805
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined index: direction /home/serverlab/public_html/inv/application/helpers/mpdf/mpdf.php 18805
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined property: mPDF::$hasOC /home/serverlab/public_html/inv/application/helpers/mpdf/mpdf.php 27911
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined property: mPDF::$hasOC /home/serverlab/public_html/inv/application/helpers/mpdf/mpdf.php 28036
ERROR - 2015-01-26 21:13:15 --> Severity: Notice  --> Undefined property: mPDF::$hasOC /home/serverlab/public_html/inv/application/helpers/mpdf/mpdf.php 9430
DEBUG - 2015-01-26 21:13:15 --> Encrypt Class Initialized
ERROR - 2015-01-26 21:13:15 --> Severity: Warning  --> Cannot modify header information - headers already sent by (output started at /home/serverlab/public_html/inv/application/modules/mailer/helpers/phpmailer/class.phpmailer.php:496) /home/serverlab/public_html/inv/system/libraries/Session.php 688
DEBUG - 2015-01-26 21:13:15 --> Final output sent to browser
DEBUG - 2015-01-26 21:13:15 --> Total execution time: 0.6427
DEBUG - 2015-01-26 21:15:01 --> Config Class Initialized

**Comment by Kovah** [comment]
You said when sending mails with an empty body?  Then enter something in the template please. The empty body could cause the error because of functions that expect a non-empty value.

**Comment by Jadaw1n** [comment]
This is the error message: `Invalid address: i`
Someone had this exact problem, too. But I can't find the thread now :(

**Comment by AbbyNormal** [comment]
No, I have email template and all fields have entries (except CC). I have created new Invoice template in: Settings->Email Templates
And I have chosen that email template in all email fileds in: System Settings->Invoices->Default/Paid/Overdue Email Template.

Am I missing something? I don't see an option for Recurring Invoice Email Template but I don't think it exists as an option...

**Comment by AbbyNormal** [comment]
The above output is generated by this section in class.phpmailer.php at line 496:
public function SetFrom($address, $name = '',$auto=1) {
    489     $address = trim($address);
    490     $name = trim(preg_replace('/[\r\n]+/', '', $name)); //Strip breaks and trim
    491     if (!self::ValidateAddress($address)) {
    492       $this->SetError($this->Lang('invalid_address').': '. $address);
    493       if ($this->exceptions) {
    494         throw new phpmailerException($this->Lang('invalid_address').': '.$address);
    495       }
    496       echo $this->Lang('invalid_address').': '.$address;
    497       return false;
    498     }

Output says: Invalid address: i div style=border:1px solid #990000;padding-left:20px;margin:0 0 10px 0; >  so there must be an error somewhere how email address is handled...

**Comment by AbbyNormal** [comment]
And here is the SMTPDebug in class.phpmailer.php
<br />SMTP -> get_lines(): $data was ""
<br />SMTP -> get_lines(): $str is "334 VXNlcm5hbWU6
"
<br />SMTP -> get_lines(): $data is "334 VXNlcm5hbWU6
"
<br />SMTP -> get_lines(): $data was ""
<br />SMTP -> get_lines(): $str is "334 UGFzc3dvcmQ6
"
<br />SMTP -> get_lines(): $data is "334 UGFzc3dvcmQ6
"
<br />SMTP -> get_lines(): $data was ""
<br />SMTP -> get_lines(): $str is "235 Authentication succeeded
"
<br />SMTP -> get_lines(): $data is "235 Authentication succeeded
"
<br />SMTP -> get_lines(): $data was ""
<br />SMTP -> get_lines(): $str is "250 OK
"
<br />SMTP -> get_lines(): $data is "250 OK
"
<br />SMTP -> FROM SERVER:250 OK

<br />SMTP -> get_lines(): $data was ""
<br />SMTP -> get_lines(): $str is "250 Accepted
"
<br />SMTP -> get_lines(): $data is "250 Accepted
"
<br />SMTP -> FROM SERVER:250 Accepted

<br />SMTP -> get_lines(): $data was ""
<br />SMTP -> get_lines(): $str is "354 Enter message, ending with "." on a line by itself
"
<br />SMTP -> get_lines(): $data is "354 Enter message, ending with "." on a line by itself
"
<br />SMTP -> FROM SERVER:354 Enter message, ending with "." on a line by itself

<br />SMTP -> get_lines(): $data was ""
<br />SMTP -> get_lines(): $str is "250 OK id=1YG47a-0002DR-L5
"
<br />SMTP -> get_lines(): $data is "250 OK id=1YG47a-0002DR-L5
"
<br />SMTP -> FROM SERVER:250 OK id=1YG47a-0002DR-L5

<br /><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  Cannot modify header information - headers already sent by (output started at /home/serverlab/public_html/inv/application/modules/mailer/helpers/phpmailer/class.phpmailer.php:496)</p>
<p>Filename: libraries/Session.php</p>
<p>Line Number: 688</p>

**Comment by Kovah** [comment]
There's something pretty wrong with the recurring invoices but I couldn't locate the error.
Just to sum up:
1. the error is thrown by the phpmailer which get's a wrong address from which to send.
2. the address is handled by `/application/modules/invoices/cron.php` and `/application/helpers/mailer_helper.php` (email_invoice function).
3. AbbyNormal's error is throwing the output of the `/application/errors/error_php.php` which is pretty weird but could be a hint that maybe an address could not be loaded or something...

**Comment by AbbyNormal** [comment]
OK, so this is happening to you to in your install?
My system is:
CentOS 6.6
Apache 2.2
PHP 5.4 
MySQL 5.5.4

**Comment by Kovah** [comment]
No, I have not tested this directly.

**Comment by AbbyNormal** [comment]
OK, this is definitely a bug. I have installed 1.1.2 version on Debian 7 with apache 2.2 and mysql 5.5.40 and the problem is the same. When executing http://your-server.com/invoices/cron/recur/jkadsnneueuAAn the output in browser is "Invalid address: i"

**Comment by Kovah** [comment]
And now we have to find him inside the code. :astonished:

**Comment by AbbyNormal** [comment]
Yes :(  I'm a sysadmin and not a coder,so I don't know how to help. At leased I helped reporting the issue and I'm willing to test the solution :)

**Comment by AbbyNormal** [comment]
Btw. I think you don't have do dig in class.phpmailer.php because it obviously works becase manually sending emails are ok. The problem is probably in those two files you mentioned:
"the address is handled by /application/modules/invoices/controllers/cron.php and /application/helpers/mailer_helper.php (email_invoice function)."

**Comment by Kovah** [comment]
It's the cron.php because the mailer_helper handles all other emails and is working fine. But I don't find the problem...

**Comment by Jadaw1n** [comment]
I think cron.php doesn't use the available method for mailing invoices, but sends them manually somehow. I changed the invoice mail method some time ago, and I assumed that this function would be used everywhere. I need to look into this...

**Comment by Jadaw1n** [comment]
Oh well... The function should always use the default template from the settings, but this is broken, since the settings key doesn't exist. Also there's no association for which invoice uses which template. So in some kind this is broken since always (and I assume the bug's also in the predecessor of this project), but no one noticed it until I extended the email templates...

If you're brave, you can check out this code:
**WARNING: I didn't test it fully yet** (but it works on my machine ™)
**Only for v1.1.1 + 1.1.2**
https://gist.github.com/Jadaw1n/4047c92a382a7238c270
Place the file here: /application/modules/invoices/controllers/cron.php

**Comment by AbbyNormal** [comment]
I can confirm it's working. Tried on testing Debian server and CentOS in production, all good :+1:

**Comment by miguelurtado** [comment]
Thanks, worked for me too.

Ubuntu Server 14.04

good :+1:
