### ISSUE TITLE
Footer in PDF

### ISSUE THREAD

**Issue by lommes** [InvoicePlane/InvoicePlane#145]
I modified some files so I can configure a HTML-footer for Invoices in the invoice settings. You can find a patch here: http://pastebin.com/v4d6ipMx

After applying this patch, you can add some HTML in System Settings -> Invoices in "PDF Footer"

Output can be styled with CSS using #footer prefix

**Comment by Kovah** [comment]
I'll take a look at it and add this to the v1.2.0 files if everything's fine.
Thanks for your contribution!
