### ISSUE TITLE
Include all fully translated language files in next release

### ISSUE THREAD

**Issue by miquel-cabanas** [InvoicePlane/InvoicePlane#148]
What do you think about including in the next release all 100% translated language files, regardless of their approval status? As of now, besides English, the languages available are: Catalan, Dutch, Estonian, French, Italian, Slovak, Spanish, Swedish and Vietnamese.

**Comment by miquel-cabanas** [comment]
Also these translations are almost finished
  - 98%: Czech, German, German-Switzerland, Portuguese, Portuguese-Brazilian,
  - 94%: Bulgarian, Croatian, Persian

**Comment by Kovah** [comment]
I would just include the most common languages. Regarding to the visitors of the website we should include Italian, German, French and Spanish (ES).

**Comment by cz-vilda** [comment]
Im finishing Czech language, in few days will be 100% ready.

**Comment by NeKRoMaNT-** [comment]
I think we must check spanish translation, it seems to merge spanish & latin american.

**Comment by Kovah** [comment]
I just sent a mail to all translators. As Crowdin (our translation backend) supports proofreading I will integrate all languages which are 100% translated and approved by a proofreader.

**Comment by trexanhvn** [comment]
I have 100% Vietnamese Language. If you need, I will send for you

**Comment by trexanhvn** [comment]
I have 100% Vietnamese Language translated. If you need, I will send for you

**Comment by trexanhvn** [comment]
I have 100% Vietnamese Language translated. If you need, I will send for you

**Comment by Jadaw1n** [comment]
@NeKRoMaNT- Oh right, I wanted to integrate your translation... Will be done until the release. (I'm currently looking for a way to "rename" the other translation, to not loose history/settings there)

**Comment by Kovah** [comment]
@trexanhvn Please submit the translations to translation.invoiceplane.com

**Comment by cz-vilda** [comment]
Czech is ready.

**Comment by lckarssen** [comment]
I noticed that the Dutch translation is complete, but not approved yet. How does proofreading work in Crowdin? Is it a privilege granted to selected translators? If so, how does one get such privileges?

**Comment by trexanhvn** [comment]
@Kovah I cannot submit. Appeared 403 Forbidden when I access to https://translation.invoiceplane.com

**Comment by Jadaw1n** [comment]
Something seems to be off atm. You can access the site via https://crowdin.com/project/fusioninvoice in the meantime.

**Comment by Kovah** [comment]
Oops. Its https://translations.invoiceplane.com with s!

**Comment by marcelorodrigo** [comment]
I think Portuguese Brazilian should be included too, it's 100% approved

**Comment by Kovah** [comment]
Cleaned up list of the languages which will be included: #160
