### ISSUE TITLE
cash method of accounting feature

### ISSUE THREAD

**Issue by justnx** [InvoicePlane/InvoicePlane#149]
support for cash method of accounting (in german: EÜR) would a very helpful and nice feature for future releases.
So we can generate a financial statement for the annual tax declaration from our existing invoice data.

A sample project in Java for adoption: http://www.jes-eur.de/?Screenshots

**Comment by Kovah** [comment]
But for this feature we would have to implement something like a deposit or at least expenses for items - something we wanted to integrate into the new version v2.
