### ISSUE TITLE
Help icon should take users to the documentation page

### ISSUE THREAD

**Issue by miquel-cabanas** [InvoicePlane/InvoicePlane#151]
Currently the help icon on the software takes users to the http://docs.invoiceplane.com/ web address which in turn points to the wiki home page at https://github.com/InvoicePlane/InvoicePlane/wiki. I think it would be more useful to take them to the wiki documentation page at https://github.com/InvoicePlane/InvoicePlane/wiki/wiki so that they can try helping themselves.

This change should improve the visibility of the application documentation and (hopefully) reduce the number of questions on the forum whose answer is "read the wiki."

**Comment by miquel-cabanas** [comment]
Additionally, I would propose
 1. to rename "wiki/wiki" as "wiki/documentation" or "wiki/help",
 2. to change the help icon into a drop-down menu with links to the documentation page and to the forum.

@Kovah, if you agree with the 2nd point, I could take care of the it.

**Comment by Kovah** [comment]
The whole docs and wiki thing will change in the following weeks as I'm working on a new wiki.

But you can change the docs link to a drop down menu if you want but change the docs.InvoicePlane.com to wiki.InvoicePlane.com
