### ISSUE TITLE
location prefix year invoice

### ISSUE THREAD

**Issue by beedesign** [InvoicePlane/InvoicePlane#153]
how do I have to place after year the invoice number ?
(automatically)
![screen](https://cloud.githubusercontent.com/assets/10184652/5712160/3a8cf382-9ab0-11e4-963c-e6c5f2b3b58b.png)

**Comment by Jadaw1n** [comment]
atm: Go to Invoice groups -> edit -> year prefix -> yes.
A more customisable solution is in the dev branch and will be released in a few weeks.
Commit: https://github.com/InvoicePlane/InvoicePlane/commit/34e2a22c7da73119524727589d96f9c5374aad40
