### ISSUE TITLE
Recurring Quotes

### ISSUE THREAD

**Issue by AbbyNormal** [InvoicePlane/InvoicePlane#158]
Hello,

my tax system doesn't allow skipping in numbers when invoices are made. So when I add recurring to three invoices which are due on the same day, and first customer doesn't pay and second and third does, then the first number is waisted and it gives a lot of complication in evidenting my bills and would get in trouble with tax system in my country.
Is there a possibility to set recurring only on quotes and when they are paid I can create an invoice so a customer can see it in his profile and download pdf invoice?

**Comment by Kovah** [comment]
No sorry, the recurring feature does only work for invoices.

**Comment by AbbyNormal** [comment]
Ok. Can I somehow hide Quotes because Invoces will be used as quotes? And will send paid invocies manually.
Btw. how yoour tax system works? Does your numbers of invices has to strictly follow numbers which have to be incrised one by one as invoices are made? How do you cope with invoces which are not paid and how do you deal with numbering then?
Thank you in advance for advice

**Comment by AbbyNormal** [comment]
The third option: I could take translation file,copy it and edit it. And swap names of Quotes and Invoices everywhere in the file. Will that do? Quotes would then be used as one time emailed paid bill(invoice) and Invoces will be used as recurring quotes. That way my bills(invoices) would follow incrementing numbers and only payed will be evidented. Don't know will there be some problems if I use the system as that? Please advice :)

**Comment by Kovah** [comment]
Just follow this thread to disable the quotes:
https://community.invoiceplane.com/t/how-can-i-disable-quotes/167

**Comment by AbbyNormal** [comment]
OK, tnx but will see how this go - I have edited my language transaltion and replaced Quotes with Invoices and vice versa. So now I have recurring quotes and when they are paid I create an invoice and send it to client :)
