### ISSUE TITLE
Release notes for v. 1.1.1

### ISSUE THREAD

**Issue by mbsarino** [InvoicePlane/InvoicePlane#159]
Hi! Where can I find the release notes for V. 1.1.1?  I'd like to check if I should upgrade from 1.1.0 or just wait till the next version which may have significant changes for me.

**Comment by Kovah** [comment]
You should always update as versions where the last number changes are bugfix releases.
But to answer your question: take a look at the wiki on the Github repository. Below the contents table there is the link to the change log.

**Comment by mbsarino** [comment]
Thanks for the info.  My apprehension is that I have made code changes to fit our needs and may hav3 to redo all those changes again.

**Comment by Jadaw1n** [comment]
Fork this repo and apply your changes then. To update you `git pull` this repo and merge the changes with yours. Use the power of git, it's really worth it ;)

**Comment by mbsarino** [comment]
@Jadaw1n :  I am not sure I understand how to do that.  I have already forked this repo as suggested.  How do I merge that with my existing files on my server?

**Comment by Kovah** [comment]
Here's a good tutorial: http://www.thinkful.com/learn/github-pull-request-tutorial/

**Comment by Jadaw1n** [comment]
Here's also a good reference: https://www.atlassian.com/git/tutorials/
It covers most git commands.

I do all this on the command line, but you can also use a gui.

To get your current changes under version control:
- Clone your repo into a new directory
- Check out the used version (e.g. git checkout 1.1.0 )
- Create a new branch with this version
- Copy all the files from the original installation in the directory
- Commit all

Now, to get the updates:
- Add InvoicePlane as new remote repository (git remote)
- Fetch the new changes: git fetch --all 
- Compare the changes: git diff HEAD invoiceplane/1.1.2
- Merge the new version (git merge invoiceplane/1.1.2) (make sure you have no uncommitted changes)
- you might get conflicts, this means that we and you changed the same line in the same file. Those have to be resolved by hand.
- If it's all good, copy the new files to the server, and follow the normal InvoicePlane update procedure.
