### ISSUE TITLE
Ship IP with more languages by default

### ISSUE THREAD

**Issue by Kovah** [InvoicePlane/InvoicePlane#160]
As discussed we'll ship InvoicePlane with some other languages by default that can be selected directly in the setup.

The following languages should be included:
- [x] Czech
- [x] Estonian
- [x] German
- [x] Portuguese, Brazilian
- [ ] Spanish
- [ ] French _(Proofreader needed)_
- [ ] Dutch _(Proofreader needed)_
- [ ] Catalan _(Proofreader needed)_

**Comment by nsina** [comment]
I can translate to Swedish.

**Comment by Kovah** [comment]
@nsina Feel free to signup at the translation repo: http://translations.invoiceplane.com/project/fusioninvoice/sv-SE
I'll add you as a proofreader then.
