### ISSUE TITLE
1.2.1. theme "bug"

### ISSUE THREAD

**Issue by DavorSaric** [InvoicePlane/InvoicePlane#161]
Just upgraded to 1.2.1 and there is a layout problem when viewing quotes or invoices or recurring invoices. Click on Quotes -> View quotes and click on Options - the scroll is shown. Also in Invoices and Recurring.

Edit by Kovah: Added image
![github_table_resonsive](https://cloud.githubusercontent.com/assets/1816101/5978953/da64ab1a-a8a3-11e4-9440-ec9edd9652e4.jpg)

**Comment by Kovah** [comment]
This is already on the todo list.

**Comment by AbbyNormal** [comment]
Great! This invoiceplane is cool project :+1:  Hope is gonna be free after all the bugs are polished :)

**Comment by Kovah** [comment]
InvoicePlane will always stay free forever. :exclamation:
