### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by cz-vilda** [InvoicePlane/InvoicePlane#162]
Im going (need) to develop "ToDo list" to have evidence of work done on my projects. Why? Usually Im working on projects and I set the invoice at the end of month for whole work. At invoice is only one item "Work on project XXX at 2014-05" with amount and list of hours done (with dates) is attached. Today, my evidence is spreadsheet. Im using InvocePlane and i want to have it at one system. So:
- during month you can evidence your work (hours, amount per hour...) per customer like you are now adding the items to invoices (maybe relation would be longer as customer-project-work) 
- items at "ToDo" list could have some states (planning, running, done, invoiced)
- at the end you will be able to generate invoice for customer with one item and with details attached OR wiht more items like ordinary invoice (only items with "done" state will be used) (one button click "make invoice")

Is it clear? Is here anybody who will use it too?

**Comment by Jadaw1n** [comment]
I welcome this contribution. We have planned light project management for v2. If you can program something, we could adapt this for v2 later :)

Also, it would be nice if you can create some logic to activate/deactivate the features (projects, time tracking), to not clutter up the interface for people who won't need this.

If you have any questions, feel free to ask here, or in the Gitter chat: https://gitter.im/InvoicePlane/InvoicePlane

**Comment by lommes** [comment]
I would absolutely use it! ATM I'm using a seperate tool, which definitly is oversized for my needs
