### ISSUE TITLE
Public quote template bug and one maybe bug

### ISSUE THREAD

**Issue by DavorSaric** [InvoicePlane/InvoicePlane#164]
There is a bug with Guest quote URL - create new quote - send email - click on guest url bellow and the page  is blank. 
Guest invoice URL is good.

**Comment by AbbyNormal** [comment]
Don't  think the problem is in /application/views/quote_templates/public/default.php because I copied for testing purpose invoice public default.php to above and there is no change, blank page.

**Comment by Kovah** [comment]
Please add different bugs as separate issues so we can handle them better and separated from each other.
