### ISSUE TITLE
Invoice numbering format

### ISSUE THREAD

**Issue by mbsarino** [InvoicePlane/InvoicePlane#167]
How do I change the invoice numbering format to prepend zeros to the number.  For example, instead of the invoice number being "Invoice # 9", I need it to be "Invoice # 000009"

**Comment by Kovah** [comment]
Settings > Invoice Groups > edit your Invoice Group > left pad
![screen shot 2015-01-29 at 18 19 07](https://cloud.githubusercontent.com/assets/1816101/5962337/82a7d85e-a7e3-11e4-8b8c-53f1455f40b3.png)

===
Please consider adding such questions to the [community](https://community.invoiceplane.com/) and **not this repository**.

**Comment by mbsarino** [comment]
My apologies.  I overlooked this one.  By the way, entering 000 in the left pad field resets to 0 on save.  I will post this again in the community as requested.

**Comment by Kovah** [comment]
You have to enter the number of digits you want to be padded: 
00009 = 4
0009 = 3

**Comment by mbsarino** [comment]
oh I see....thanks for the help!!!

**Comment by mbsarino** [comment]
I entered "3" in the left pad at first but the numbering format on a new
invoice didn't change.  I then edited the "Prefix" with "0" thinking that
would solve it but it only provides one "0" prefix.

**Comment by Kovah** [comment]
The setting does not change existing invoices but new ones will get the prefix.

**Comment by mbsarino** [comment]
I've tried on new invoices only.  as mentioned, entering "3" in the left pad does not add the zeros at the front (it doesn't change the numbering output).  Changing the "Prefix" setting to "0" while still having "3" in the "Left Pad" field only adds a single zero.

**Comment by Kovah** [comment]
Then something is broken with the padding. Which version do you use?

**Comment by mbsarino** [comment]
I use v 1.1.0

**Comment by Kovah** [comment]
Uhm... v1.1.2 is the current version. Please update: https://community.invoiceplane.com/t/invoiceplane-v1-1-2-released/279

**Comment by mbsarino** [comment]
@Kovah:  I just found out the reason why thee "left pad" setting didn't work for me origninally.  Our invoices have 6 digits and currently use the last 3 digits for the numbering.  The "left pad" setting I originally used (3) did not produce the zeros in the front, making me think that the padding doesnt work.  This is because the number setting for the pad actually signifies the nuber of digits to display and not the number of zeros to prepend.  Thus, a setting of "3" would produce an invoice number of :"123" and a setting of "6" would produce "000123"

**Comment by Kovah** [comment]
Ah perfect!
No bug! :tada:
