### ISSUE TITLE
Update translations in crowdin

### ISSUE THREAD

**Issue by lommes** [InvoicePlane/InvoicePlane#171]
My PR introduced some new entries which are used during setup. These entries can not yet be translated at crowdin.

**Comment by Kovah** [comment]
New translation strings will be added to Crowdin shortly before the release of the containing version.

**Comment by lommes** [comment]
Ok, PR was merged to 1.1.2 so i thought it would be about time. Thanks for the info.

**Comment by Kovah** [comment]
Oh I thought it was 1.2.0! Sorry
