### ISSUE TITLE
System settings fail silently if timezone is not properly declared

### ISSUE THREAD

**Issue by dekomote** [InvoicePlane/InvoicePlane#32]
System settings fail silently if timezone is not properly declared.

The code in question is https://github.com/InvoicePlane/InvoicePlane/blob/master/application/modules/settings/controllers/settings.php#L140

This can be frustrating for users installing the software on some hosting providers.

**Comment by lommes** [comment]
I came across this issue on several systems (some time ago) where, depending on OS and PHP-version, date.timezone in php.ini had no value and systems timezone was not available to PHP

There should be a warning in E-STRICT (see http://php.net/manual/de/function.date-default-timezone-get.php#74632). It seems that in PHP prior 5.4 a value was guessed if no value was present.

**Comment by Jadaw1n** [comment]
Do I assume right, that this code should work better?
`new DateTime(null, new DateTimeZone(date_default_timezone_get()));`
As per the documentation, if date_default_timezone_get() can't get any useful value it just returns "UTC". This is a valid string for DateTimeZone. And if this is valid, then new DateTime should also work.
And if date.timezone is not valid there are enough other errors thrown.

**Comment by lommes** [comment]
Yes, that seems to fix it and it still triggers a Warning.

Same issue should appear when creating invoices and quotes because DateTime is also used in:
application\helpers\date_helper.php
application\modules\invoices\models\mdl_invoices.php
application\modules\quotes\models\mdl_quotes.php

I was able to reproduce the error on Win 7 and xampp. When you use development as ENVIRONMENT in index.php many warnings occur because of the missing timezone.

**Comment by lommes** [comment]
An alternative would be to modify setup to check timezone. If that's your prefered approach I can provide a PR for that.

**Comment by lommes** [comment]
In my opinion it would be best to include a check in setup with a warning and setting the timezone at an early point of each request so https://github.com/InvoicePlane/InvoicePlane/pull/154 and the modification of CI core files would be not necessary

**Comment by Jadaw1n** [comment]
Yeah it's probably better if we check this in the setup. If something new uses DateTime the same problem will happen again. So if you can submit your PR... :)
