### ISSUE TITLE
[1.6.2?] More digits for item quantity

### ISSUE THREAD

**Issue by zeitschlag** [InvoicePlane/InvoicePlane#731]
> I wonder how difficult it would be to make this a configurable setting?  Some installations only need 2 decimals, and some need 3-4.  One of my clients is in the pharmacy industry and they require 8 decimal places as they dispense drugs by the milliliter and it has to calculate to a deep precision.

At the moment, only two digits are supported, we should make this more flexible.

We have to change the type of the database column from `DECIMAL` to `FLOAT` or `DOUBLE`. And then we probably have to change some number-formatters, too. To demonstrate this, there's an [example here](https://github.com/zeitschlag/InvoicePlane/commit/983176470173db5d1239b007b6293892b5ba4568)

**Comment by nielsdrost7** [comment]
I've created PR #780 for this issue. Should be mergeable into `develop`
I've checked and it cannot be merged into `release`, which is OK.

**Comment by Cabji** [comment]
This would be handy. I am a trade contractor and we usually bill at some sort of "day rate" where a day is 8 hours. To charge 11 hours, instead of converting the unit price to an hourly rate I prefer to just change the days amount so would need 1.375 for 11 hours, but IP wants to use either 1.37 or 1.38.

**Comment by spacecabbie** [comment]
Is there any  status on this ?

**Comment by nielsdrost7** [comment]
@Cabji @spacecabbie my apologies, I've overlooked this one for a while.

I'm putting this one on the list for v1.6.2.
The PR serves as an example, so I'll have to take a look into actual solution.

It will involve a database update, just so you know.

**Comment by spacecabbie** [comment]
No worries niels, if you want after you had a look over and reply here that it should work I'm perfectly willing to give it a test run.

**Comment by naui95** [comment]
Moving it to a further update. Implementation must:
- [ ] update decimals in DB for fields (which ones)
- [ ] implement possibility to choose the front end display
