### ISSUE TITLE
[1.5.12?] Update JS-dependencies

### ISSUE THREAD

**Issue by zeitschlag** [InvoicePlane/InvoicePlane#736]

**Comment by nielsdrost7** [comment]
So I did some work on the Composer and Javascript packages
- updated composer.json
- updated package.json to point to the latest possible packages
- `npm audit fix --force` was run, which could mean breaking changes
- I committed the yarn.lock file before `npm audit fix --force`

**Comment by nielsdrost7** [comment]
When you build the Javascript packages with `grunt build` you'll get an error:
```The implementation option must be passed to the Sass task```
We have to make sure we've added `node-sass`
Then In your gruntfile, you then need to add node-sass as _requirement_ and add the define constant as implementation option:
```
const sass = require('node-sass');

require('load-grunt-tasks')(grunt);

grunt.initConfig({
    sass: {
        options: {
            implementation: sass,
            sourceMap: true
        },
        dist: {
            files: {
                'main.css': 'main.scss'
            }
        }
    }
});
```
