### ISSUE TITLE
Post Install error (with MySQL 8 installed)

### ISSUE THREAD

**Issue by r007ops** [InvoicePlane/InvoicePlane#747]
A brand new fresh install on a LEMP server, set-up completed successfully, got to login page, entered details and straight away got the following.

![error_github](https://user-images.githubusercontent.com/85933917/128388298-2647cf82-9992-4e64-b920-ef48b8bf4fee.png)

**Comment by clockwiseq** [comment]
Can you give us a few more details like PHP version, MySQL version, etc.?

**Comment by r007ops** [comment]
Apologies.

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

PHP 7.4.3 (cli) (built: Jul  5 2021 15:13:35) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

mysql  Ver 8.0.26-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))

nginx version: nginx/1.18.0 (Ubuntu)

**Comment by dfear** [comment]
My fix for this is to login to my VPS and run and the following command (as root):
mysql -u root -p -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION';" 

it's not a permanent fix. Needs to re-done every time MySQL/MariaDB package is updated.

**Comment by UnderDogg** [comment]
Great fix @dfear !
@r007ops advice is to apply that fix in your MySQL 8 setup. Alternative is to downgrade, but in MySQL 5.7 you'll have this same problem.
It's a configuration change that showed up between MySQL 5.6 and 5.7

**Comment by nielsdrost7** [comment]
So I'm going to close this issue with referrence to @dfear 's fix
