### ISSUE TITLE
[Cloudflare culprit] While sending an email I get the message: "It seems that the application stuck because of an error" (email is still sent)

### ISSUE THREAD

**Issue by mbassiouny33** [InvoicePlane/InvoicePlane#749]
Hi there,

I am trying to send and invoice with invoiceplane, when I click on send, it takes a while to load then it shows "It seems that the application stuck because of an error."

and it keeps loading in the end it shows "email sent successfully" and the email is actually sent without any problems. 

I enabled debug mode in ipconfig.php file (I don't have the option to enable it in the UI btw, thought the documentation says it is possible). Even with debug mode On I don't get any explicit error messages.

In the end the email is sent, so it is fine, but it takes up to 1 minute of loading to send the email and the fact it shows an error message then it sends the email is a bit annoying. 

I use SMTP to send emails.
My site is running behind Cloudflare and I modified `$config[‘sess_match_ip’] = env(‘SESS_MATCH_IP’, false);` to avoid getting kicked out.

Any help to fix this issue will be appreciated.

Thanks

**Comment by UnderDogg** [comment]
Check your google chrome console. It might be, that your console (or your network tab) is giving you the error, while it's not showing up in the debug log

**Comment by mbassiouny33** [comment]
Hi,  Thanks for the hint. Unfortunately nothing is being printed in the console and there is nothing unusual in the network tab...
any other hints? Thanks

**Comment by UnderDogg** [comment]
I don't have other hints.
Is it a local install or somewhere on a server?
I need steps to reproduce (with lots of details)

**Comment by mbassiouny33** [comment]
Hi again and thanks for your reply.

It is installed on a server. If you wish (and have the time) I can give you access to that installation 

I tried to isolate the problem, the test user's language was not set to English (it was set to Arabic), but I changed it to English and the issue still happens.

I tried https://github.com/sameersbn/docker-invoiceplane with multiple languages and it worked just fine without any issues, but I don't want to rely on it as it is no longer maintained, and uses a version with the xss vulnerability + the invoice pdf folder is not accessible outside the container which makes it a pain to customize. 

My teps:
- Created a client (name with normal latin characters -nothing Chinese, Arabic, etc).
- invoices, create new invoice, I don't have to use a product to reproduce the issue, just putting any onetime values or leaving the invoice empty. (But the issue still happens when adding products). [only a json appears in console summarizing the invoice details]
- Options. send email, I type the email (nothing shows on console)
- "it seems that the application stuck because of an error" appears (nothing on console)
- "Email successfully sent" still nothing appears in console.

Since the dockerized version worked I am suspecting there is something in my environment that the app does not like, I thought of my php version? I tried both php7.4 and 7.2 (with the same installation) and the issue persists. Maybe mysql version?...

**Comment by UnderDogg** [comment]
Yes, check out the MySQL version. If the server has MySQL 5.7 or 8, it's something to focus on.
Sameer thought had MySQL 5.6 if I'm not mistaken.

If it's not reproduced locally it's very difficult to resolve.
Think of the email settings. Did you send it through Gmail? Imap?

**Comment by mbassiouny33** [comment]
did some more testing and I am able to reproduce the error. It has nothing to do with foreign languages, I used English only.

Setup 1:
- ip 1.5.11
- apache 2
- Php 7.2 (and 7.4)
- mysql 8
- Ubuntu 20

Setup 2:
- ip 1.5.11
- nginx
- Php 7.3
- mariaDB 10.3
- debian 10


> Think of the email settings. Did you send it through Gmail? Imap?

Through a self-hosted email. Since the email seemed to work fine in sameer's dockerized version, I don't think it is related to my email settings. Samer's version was using ip 5.9, I am able to reproduce this with 5.11. I would point the fingers to something that went wrong with version 1.5.11 I will try the older version on the same setup and see if the issue happens with 5.9 too

**Comment by mbassiouny33** [comment]
**Update:**

Found it! Cloudflare (CF) is the culprit. just disabled the CF proxy and it worked. I have already modified `config[‘sess_match_ip’]` because when using behind CF I was getting signed out every 1-2 minutes. But apparently this is not the only issue caused by CF. Seems InvoicePlane does not like cloudflare's proxy... are there any recommended known-good settings to adjust for usage with CF?

**Comment by kenemedia** [comment]
I do have the same issue with CF and sending mails. Other issue which you perhaps also have noticed, error 520, randomly when using InvoicePlane. Not able to discover why this is being triggert recently.

**Comment by nielsdrost7** [comment]
So I'm going to close this issue. We cannot control what happens on CloudFlare

**Comment by mbassiouny33** [comment]
@nielsdrost7 actually, I don't really blame it on CF, most web services work fine with CF. It more of a compatibility issue. Not fair to throw the blame on them entirely. InvoicePlane is made in a way that does not work fine with CF.
