### ISSUE TITLE
[request] Adding XB Riyaz font by default (to avoid failure and fatal error with Arabic invoices)

### ISSUE THREAD

**Issue by mbassiouny33** [InvoicePlane/InvoicePlane#750]
Hi there,

I know IP comes with a version of mpdf that is stripped of some fonts, but I think that IP should come with the minimum amount of fonts required for the app to run out of the box without forcing the user to add fonts if they want to use non-English language.

For instance, Arabic invoices seem to require XB Riyaz fonts family, when generating an invoice for a user with language set to Arabic, I get :

> Type: Mpdf\MpdfException
> 
> Message: Cannot find TTF TrueType font file "XB Riyaz.ttf" in configured font directories.
> 
> Filename: /var/www/invoiceplane/vendor/mpdf/mpdf/src/Fonts/FontFileFinder.php

**The simple solution:**
For other users who face this issue, simply add the missing fonts from mpdf's official repo
https://github.com/mpdf/mpdf

copy fonts from: https://github.com/mpdf/mpdf/tree/development/ttfonts
to:  PATH_TO-INVOICEPLACE/vendor/mpdf/mpdf/ttfonts

Just thought I would flag this, so maybe fonts could be added in future releases of IP. Thanks

**Comment by AmarTinawi90** [comment]
Thank you very much
