### ISSUE TITLE
[1.5.12?] Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [InvoicePlane/InvoicePlane#751]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by UnderDogg** [comment]
Hey there @zidingz and @huntr-helper
Thank you for your message. Can you email it to mail@invoiceplane.com?

**Comment by zidingz** [comment]
Will do! Expect an email within the hour. And if it'll save you some hassle: https://github.com/InvoicePlane/InvoicePlane/pull/752

**Comment by dagelf** [comment]
PR #797

**Comment by JamieSlome** [comment]
@nielsdrost7 @dagelf - just for your reference, the three reports can be found here:

https://huntr.dev/bounties/f33a2379-e969-4983-bd37-1beac767cb95/
https://huntr.dev/bounties/c85e770c-a183-4c8d-a9a3-fb7a7b48e876/
https://huntr.dev/bounties/eae10dcc-6fad-44eb-a428-a27f5ef0144f/

They are all private and only accessible to maintainers with repository write permissions 👍

**Comment by fgiering** [comment]
I think this should be a [security.txt](https://securitytxt.org/) since its a [RFC](https://datatracker.ietf.org/doc/html/rfc9116)

**Comment by naui95** [comment]
> I think this should be a [security.txt](https://securitytxt.org/) since its a [RFC](https://datatracker.ietf.org/doc/html/rfc9116)

Hi @fgiering,  thank you for the hint. The `security.md` file was setup to comply with GitHub standards (https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) anyhow we will consider implementing the RFC 9116 informational advise in future versions.

**Comment by fgiering** [comment]
I see. Thanks.
