### ISSUE TITLE
Overview does not count paid invoices

### ISSUE THREAD

**Issue by Cantibra** [InvoicePlane/InvoicePlane#756]
Hey there,

is there any issue known that the paid invoices doesn't count in the overview?
The offer overview works great.

Thank you! =)

<img width="1392" alt="Bildschirmfoto 2021-09-14 um 12 16 09" src="https://user-images.githubusercontent.com/87247206/133240613-e6025b8a-9b6e-4272-9e60-838693bebb2b.png">

**Comment by nicoletta-maia** [comment]
Hi @Cantibra,
I have tried with version _1.5.11_ and it seems to me that it counts the _Payments_ entered for the invoices, not the total amount of the invoice.
I hope it helps you :)

**Comment by Cantibra** [comment]
Hi @nicoletta-maia 

Yeah that answer is helping me.
I've not entered a payment for the invoice.

I add now a payment and it is working.

Great, thank you! =)
