### ISSUE TITLE
Paypal API interaction with Client ID and Secret

### ISSUE THREAD

**Issue by ririko5834** [InvoicePlane/InvoicePlane#757]
Please create PayPal API integration to allow us to use Client ID and Secret for Paypal interaction. As on normal personal PayPal accounts, you can't get PayPal express credentials. 
Here is PayPal API documentation https://developer.paypal.com/docs/api/reference/api-requests/

**Comment by NoodlesDev987** [comment]
I have same problem that I can't get paypal express credentials

**Comment by nielsdrost7** [comment]
See PR #816 , I'm closing this issue

**Comment by anondev-sudo** [comment]
This wasn't fixed, just stripe integration, not paypal.

Also when there will be release?

**Comment by nielsdrost7** [comment]
@anondev-sudo the release depends on a couple of things.
In the meantime you can check out the `development` branch and maybe merge in PR #831. It is prepared for PHP 8.1 compatibility.

**Comment by anondev-sudo** [comment]
Can you reopen this? The PR was for stripe outdated fix, but not foe PayPal to use client id and secret new api. The express api is outdated and doesn't work on personal PayPal accounts while you can obtain client id and secret also on personal accounts to accept payments

**Comment by nielsdrost7** [comment]
It's reopened. Hope you can make a pull-request for the fix.

**Comment by naui95** [comment]
@anondev-sudo @ririko5834 are you available to make some testing? We set up a new payment interface that supports Paypal (and Stripe). We would be grateful if you guys could do some testing.
