### ISSUE TITLE
Delete PDF files when invoice is deleted

### ISSUE THREAD

**Issue by NoodlesDev987** [InvoicePlane/InvoicePlane#764]
When invoice is deleted from dashboard, PDF files for that invoice should be removed too from the server.

**Comment by clockwiseq** [comment]
I agree and believe this can be classified as a bug.  I will take it a step further and say that only a PDF should be generated when necessary for a particular function like sending in an email or viewing the PDF online and then be immediately deleted afterwards.

**Comment by nielsdrost7** [comment]
`application/modules/invoices/controllers/Ajax.php` line 463

**Comment by dagelf** [comment]
Everyone might not agree with this, it might be a feature. Sometimes you want copies of what happened... it should be an option.

**Comment by nielsdrost7** [comment]
Closing this, need to rethink this for the future
