### ISSUE TITLE
recurring Invoices not being generated.

### ISSUE THREAD

**Issue by mbassiouny33** [InvoicePlane/InvoicePlane#766]
Hi there,

I have setup recurring invoices since 2 months. some of them simply are not generated for no reason!

Example:
- 07/28: I create first invoice manually + setup recurring
- 08/28/2021: invoice created and sent to client
- 09/28/2021: invoice not created 

Knowing that I changed nothing, the invoice has been there and worked fine for the first time and it's still on "recurring invoices" list and shows next date on 10/28/2021. I checked the logs at application/logs for 28/09 but there is nothing useful there... 

Any suggestions on how to debug this?

Thanks

**Comment by welsi13** [comment]
Hi,
I'm having a similar issue with reoccurring invoices. One of them works well, while the others don't. I already deleted them and created them once again, but they are not generated. I can't even reach the update-page using the adopted link and key as stated in the wiki (https://wiki.invoiceplane.com/en/1.5/modules/recurring-invoices).

Any ideas?
Thanks.
