### ISSUE TITLE
[1.5.12?] Issue with IP-473 Client Statements, as staged in release branch at 19/11/2021

### ISSUE THREAD

**Issue by xwni** [InvoicePlane/InvoicePlane#773]
Hi,

There is a bug introduced in the release branch as it stands today, from the commit to merge code for IP473 Client Statements. 

I'm happy to see this feature code being merged, since I need this functionality.  However the merge introduces a new bug surrounding date manipulation.  

Specifically, in the file  "**application/modules/statements/controllers/Statements.php**", this has been changed to ignore the configured date format setting -  it will only work for installations using "d M, Y". 

There are a couple of places in the Statements.php file similar to the below. 

  @@ -63,13 +63,21
  - $statement_start_date = strtotime($this->input->post('statement_start_date'));
  +// BUG : strtotime is not recognising the date format d M,Y" and changing the date
  +// $statement_start_date = strtotime($this->input->post('statement_start_date'));
  +$date_time = date_create_from_format("d M,Y", $this->input->post('statement_start_date'));
  +$statement_start_date = $date_time->getTimestamp();

This seems to be an incorrect fix.  Hard coding "d M, Y" seems wrong.  

Can the code instead pull in the system date format as configured on the IP System Settings page.   For example for my local installs of IP, I have chosen to use an ISO styled date "Y-m-d".   In my case, strtotime works well, but the code should really check the system settings to check and work with the chosen date format.

**Comment by nielsdrost7** [comment]
Hi,
Thanks for the report.
You actually mean the `release` branch, correct?

Go ahead and make a pull-request with your solution and we'll take a look.

**Comment by nielsdrost7** [comment]
@xwni can you make that pull-request?

**Comment by xwni** [comment]
Yes, i mean the <release> branch.   So the code is not in a bundled/versioned release of IP1.x yet. 

That said, it's a good feature.    

I'm not currently set up to develop using github.  For now, in my local installation - I have changed these lines back to use the php strtotime function, since that "works for me"  -  but I accept it's probably not a correct answer, and not suitable for a pull request. 

I'm unfamiliar with scope - what IP's variables/functions i might have access to from in that Statements.php function?  Is there a utility function that can return the date format as chosen in the IP settings page?    We could perhaps feed that into date_create_from_format, instead of hardcoding "d M,Y".

**Comment by nielsdrost7** [comment]
I'm closing this. I'm reverting the `release` branch.
Focus on the development branch to see future updates, etc.
