### ISSUE TITLE
Currency Code missing

### ISSUE THREAD

**Issue by gokkstudio** [InvoicePlane/InvoicePlane#775]
Hello, I'm missing a currency code for "Croatian Kuna" (HRK), how can I add it manually. Thanks

**Comment by nielsdrost7** [comment]
Can you be more specific about add screenshots for:
- where you are missing that currency
- top right corner click on settings, then click on currency

This is not really an 'issue', but I won't close it ... for now.
Let's see those screenshots

**Comment by nielsdrost7** [comment]
Ok, I'm going to close this issue for lack of screenshots.
As soon as you have them try to re-open with appropriate information
