### ISSUE TITLE
[1.5.12?] Language management not working properly

### ISSUE THREAD

**Issue by der-peer** [InvoicePlane/InvoicePlane#784]
**User language setting not shown correctly**
_Settings -> User Accounts:_
Language field does update database field `ip_users.user_language`, but always shows current default language, not the user selected language.

**Missing language fallback:**
If user logs in, whose selected language is missing for whatever reason, error page pops up:
`An Error Was Encountered  
Unable to load the requested language file: language/XXXX/ip_lang.php`
I think it's ok to fail if the default language as set in _Settings -> System Settings -> Language_ is missing.
But if a user language is missing, it should automatically fall back to the default.
When the error page is hit, there is no way to get back to the login page.

**Rename fields:**
To clarify order, fields should be named accordingly
Settings -> System Settings -> Language ==> (System) Default language
Settings -> User Accounts -> User Form ==> User language

**Comment by nielsdrost7** [comment]
> Missing language fallback:
If user logs in, whose selected language is missing for whatever reason, error page pops up:
An Error Was Encountered Unable to load the requested language file: language/XXXX/ip_lang.php
I think it's ok to fail if the default language as set in Settings -> System Settings -> Language is missing.
But if a user language is missing, it should automatically fall back to the default.
When the error page is hit, there is no way to get back to the login page.

See issue #785 and it's solution

**Comment by nielsdrost7** [comment]
Closing this, need to rethink languages for the future releases.
For now: First download the translations for your language and place them in the proper directory.
There should be no language problems then.

We were working with non-existent translations
