### ISSUE TITLE
[MySQL Version requested] Invalid date in the invoice data.

### ISSUE THREAD

**Issue by raguay** [InvoicePlane/InvoicePlane#789]
I've created one invoice and now it can't view invoices at all. I deleted everything and reinstalled. The same error is happening. The error is:

A Database Error Occurred

Error Number: 1525

Incorrect DATE value: '0000-00-00'

SELECT SQL_CALC_FOUND_ROWS ip_quotes.*, ip_users.*, ip_clients.*, ip_invoice_sumex.*, ip_invoice_amounts.invoice_amount_id, IFnull(ip_invoice_amounts.invoice_item_subtotal, '0.00') AS invoice_item_subtotal, IFnull(ip_invoice_amounts.invoice_item_tax_total, '0.00') AS invoice_item_tax_total, IFnull(ip_invoice_amounts.invoice_tax_total, '0.00') AS invoice_tax_total, IFnull(ip_invoice_amounts.invoice_total, '0.00') AS invoice_total, IFnull(ip_invoice_amounts.invoice_paid, '0.00') AS invoice_paid, IFnull(ip_invoice_amounts.invoice_balance, '0.00') AS invoice_balance, ip_invoice_amounts.invoice_sign AS invoice_sign, (CASE WHEN ip_invoices.invoice_status_id NOT IN (1, 4) AND DATEDIFF(NOW(), invoice_date_due) > 0 THEN 1 ELSE 0 END) is_overdue, DATEDIFF(NOW(), invoice_date_due) AS days_overdue, (CASE (SELECT COUNT(*) FROM ip_invoices_recurring WHERE ip_invoices_recurring.invoice_id = ip_invoices.invoice_id and ip_invoices_recurring.recur_next_date <> '0000-00-00') WHEN 0 THEN 0 ELSE 1 END) AS invoice_is_recurring, ip_invoices.* FROM `ip_invoices` JOIN `ip_clients` ON `ip_clients`.`client_id` = `ip_invoices`.`client_id` JOIN `ip_users` ON `ip_users`.`user_id` = `ip_invoices`.`user_id` LEFT JOIN `ip_invoice_amounts` ON `ip_invoice_amounts`.`invoice_id` = `ip_invoices`.`invoice_id` LEFT JOIN `ip_invoice_sumex` ON `sumex_invoice` = `ip_invoices`.`invoice_id` LEFT JOIN `ip_quotes` ON `ip_quotes`.`invoice_id` = `ip_invoices`.`invoice_id` ORDER BY `ip_invoices`.`invoice_id` DESC LIMIT 15

Filename: core/MY_Model.php

Line Number: 220

---

I'm using PHP7.4 on my local computer (MacBook Pro 2021 with M1 chip) installed using Homebrew.

**Comment by nielsdrost7** [comment]
Which MySQL version are you using

**Comment by nielsdrost7** [comment]
We can't support MySQL 8.
The reason? Thing like you just posted. Things that MySQL changed.
Maybe on another site (Stackoverflow) there's another solution to deal with MySQL 8. Hopefully you can find that solution. Or switch to MariaDB?

Best solution: Switching to MariaDB (ask your host)
Second best solution: https://github.com/InvoicePlane/InvoicePlane/issues/747#issuecomment-893756309

We can't support MySQL 8. Now you know why.

**Comment by chanx** [comment]
maybe you can try this

#769 https://github.com/InvoicePlane/InvoicePlane/issues/769#issuecomment-1054316094
