### ISSUE TITLE
Recurring invoices do not copy invoice_discount_*

### ISSUE THREAD

**Issue by pimvanpelt** [InvoicePlane/InvoicePlane#790]
Reproduce:
- Create an invoice with arbitrary items
- Set the invoice to be an arbitrary % or fixed value discounted, for example 100%
- Save the invoice
- Create a recurring from that saved invoice, interval doesn't matter, choose 1d recurring

Expected result:
- The generated recurring invoices have the discount (either invoice_discount_percent or invoice_discount_amount) applied

Actual result:
- The generated recurring invoices do not have the discount applied.

This might be fixed in application/modules/invoices/models/Mdl_invoices.php around line 267 in function copy_invoice(). 
We would want to copy forward fields invoice_discount_percent and invoice_discount_amount into the $target_id invoice. There may be other fields we might want to copy forward. I can give a go at a PR although I'll have to read up on PHP :-)

**Comment by pimvanpelt** [comment]
As a partial (perhaps sufficient) fix - we can copy forward these fields in invoices/controllers/Cron.php which I'll do now.

**Comment by nielsdrost7** [comment]
with the merging of this PR in the development branch, the problem is resolved.
