### ISSUE TITLE
When on a project and creating task, it doesn't populate the project field, so task gets created without project. 

### ISSUE THREAD

**Issue by dagelf** [InvoicePlane/InvoicePlane#792]
The project field needs to be populated properly when creating a task from the project page.

**Comment by nielsdrost7** [comment]
Can you show the steps to reproduce?
With some details please.

**Comment by clockwiseq** [comment]
@dagelf, could you give an example as well as any errors that are in the console of the browser?  If you need help/instructions on how to do that, let me know.

**Comment by nielsdrost7** [comment]
Missing information, closing the issue
