### ISSUE TITLE
Password for invoice link too (not just PDF)

### ISSUE THREAD

**Issue by dagelf** [InvoicePlane/InvoicePlane#793]
Add a password prompt before showing the invoice, if a password was added.

**Comment by nielsdrost7** [comment]
Insufficient question

**Comment by dagelf** [comment]
This one is straightforward:

When setting a password on an invoice, then the URL should point to a
password login page before the invoice could be viewed online,
For bonus points - a download link to the password protected PDF can also
be added on this page.
