### ISSUE TITLE
Bank statement functionality (and import and reconciliation)

### ISSUE THREAD

**Issue by dagelf** [InvoicePlane/InvoicePlane#794]
This functionality will greatly boost the usefulness of this project.

**Comment by nielsdrost7** [comment]
Insufficient question

**Comment by dagelf** [comment]
To add more details:

A good invoicing system needs to be able to see if payments were made or
not.
Now Invoiceplane can do this for online payments.
But it lacks the functionality to see this from bank transfers or other
accounts.
Most similar systems have a function where an account with a list of
transactions can be held, and where these transactions can be between
accounts, and where a list of these transactions can be imported from
different formats, and where the transactions can be matched between
accounts to see if transfers or payments took place.
Many people downloading this project will look for this functionality, and
without it the program won't work for them.

The purpose of this ticket is to find information on how implementable this
functionality is, before spending hours analyzing the source code. But to
analyze the source the first question is does the program keep accounts?
That can be found out by looking at the database structure. Is each invoice
just an entry in one big table, or are the multiple tables? Is there a
field on the table that says which account it belongs to, or is it just
"paid" or "unpaid"? If it is the former, then the next step would be to
just create an account view page, and then an import and export page, and
then a payment reconciliation page. If it is the latter, then the logic of
the program needs to be analyzed to see if "paid" and "unpaid" can become
an account number field and an accounts table be added, or if "paid" and
"unpaid" functionality should remain, and just an accounts field be added
instead.

**Comment by dagelf** [comment]
If issues remain open then it can give ideas to other developers to make pull requests for those issues. Some developers might just be looking for something to do, the plan is to give them a chance so make the work easier. If its closed then the chances of them finding it is just a little bit less. But then again seeing issues getting closed quicly might be what attracts them to the project in the first place. :-)

**Comment by clockwiseq** [comment]
I agree with you, and I feel that this will be a great addition to the application, but we need more information.  Please make sure that when you submit an issue to follow our [contributing guidelines](https://github.com/InvoicePlane/InvoicePlane/blob/da2ff1cb1f82341d61e08888602807f30995350f/CONTRIBUTING.md).
