### ISSUE TITLE
php 7.4 EoL in 9 months. php 8.1 required 

### ISSUE THREAD

**Issue by muddydev** [InvoicePlane/InvoicePlane#798]
Since PHP 7.4 is completely EoL in 9 months wouldn't it be better to build a version for PHP 8.1? 

I deployed invoiceplan on latest PHP to testand it is completely broken

<html>
<body>
<h3 style="line-height: 3rem; margin: 0px 0px 1.5rem; overflow: hidden; text-rendering: optimizelegibility; font-size: 1.25rem; font-weight: 500; color: rgb(51, 51, 51); font-family: &quot;Fira Sans&quot;, &quot;Source Sans Pro&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Currently Supported Versions</h3>

Branch | Initial Release | Active Support Until | Security Support Until
-- | -- | -- | --
7.4 | 28 Nov 2019 | 2 years, 2 months ago | 28 Nov 2021 | 2 months ago | 28 Nov 2022 | in 9 months
8.0 | 26 Nov 2020 | 1 year, 2 months ago | 26 Nov 2022 | in 9 months | 26 Nov 2023 | in 1 year, 9 months
8.1 | 25 Nov 2021 | 2 months ago | 25 Nov 2023 | in 1 year, 9 months | 25 Nov 2024 | in 2 years, 9 months

<br class="Apple-interchange-newline">
</body>
</html>PHP's support commitments
Branch	Initial Release	Active Support Until	Security Support Until
[7.4](https://www.php.net/downloads.php#v7.4.27)	28 Nov 2019	2 years, 2 months ago	28 Nov 2021	2 months ago	28 Nov 2022	in 9 months
[8.0](https://www.php.net/downloads.php#v8.0.15)	26 Nov 2020	1 year, 2 months ago	26 Nov 2022	in 9 months	26 Nov 2023	in 1 year, 9 months
[8.1](https://www.php.net/downloads.php#v8.1.2)	25 Nov 2021	2 months ago	25 Nov 2023	in 1 year, 9 months	25 Nov 2024	in 2 years, 9 months

Logs ; - 

* SNIP *

**Comment by qroft** [comment]
Ok, i was wondering why my version was not working any more and can confirm that it does not work anymore based on the PHP version of my webhost. The only for me that worked out, was to create a server file indicating a different PHP version for the scripts.
But i am sure that my webhost won't support this too long.

So the main question now is if this project is "dead" or how hard it would be to adapt the current version to PHP 8.x !?

**Comment by clockwiseq** [comment]
@nielsdrost7, what are your thoughts on us reviewing the requirements and tasks required to become compatible with PHP 8.1?

**Comment by MartinHotmann** [comment]
Thanks for your request.

Let me first clear some things up.

1. InvoicePlane is based on the PHP Framework "[CodeIgniter v3](https://github.com/bcit-ci/CodeIgniter)" which is not upgradable to v4.
Codeigniter v3 requires PHP >=5.3.7 which includes PHP 8, but I have to check, if and on which version exactly PHP 8 support is added.
2. PHP 7.4 is still supported and untill the security support runs out, there are no concerns at all. Please check here: https://www.php.net/supported-versions.php

Please notice, that I might release new versions, but I do not actively develop the application. I sponsor/host the server/website etc and the infrastructure InvoicePlane is currently running on.

Depending on if PHP 8 support is added in a newer CodeIgniter v3 version I could run some tests and release a test build which you guys could test to see if it runs smoth.

As you see from their latest commits (ATM): https://github.com/bcit-ci/CodeIgniter/commit/dd249ea85f54f200267bb206e6cee23497cbe2e2 they are working on PHP 8.1 support, so we could give it a try once they release a newer version. But ATM the last release was from 2019 (v3.1.11), which is included in the lastest InvoicePlane release.

**Comment by nielsdrost7** [comment]
My thoughts:
1) I'm sorry, but the stacktrace in the opening post is completely unreadable
2) InvoicePlane is not dead. It relies on CodeIgniter v3 and they're working on getting it ready for PHP 8 (as it seems)

3) As soon as CodeIgniter makes a version, then we can make a version to test (or sooner).

4) If you want to make a test version, you point the codeigniter version to 'dev-master' or something like that.
We cannot make a release with pointing to 'dev-master' of CodeIgniter.
We have to keep pointing to a real release, like 3.11, 3.12, etc

**Comment by clockwiseq** [comment]
Looks like CI 4.1 supports PHP 8.  We need to determine what other dependencies we have so that we can upgrade to 4.1 and the identified dependencies.  Let's have someone try this in a new branch and see what happens.  We need them to note what else breaks so we can determine what versions of those dependencies we need to upgrade as well.

**Comment by MartinHotmann** [comment]
@clockwiseq but CI v3 is not upgradable to CI v4. It's not meant to be. Anyway we can try it, but I think there will be very much to do.

**Comment by nielsdrost7** [comment]
For Laravel:
- Write down the screens that we have
- write down the tables that we have and how they relate
- write down what we want to do better in each screen (database table), let's say `modules`, that's easier.
- For each module we'll then have a plan.
- logging in etc is the `core` module
- Figure out what we want to do first... per module
- after that ... it needs to be `pluggable` so questions like "I need to connect to api xyz" can easily be answered.

Good discussion

**Comment by TheGranadilla** [comment]
Hey :)
Useless comment, just to say thanks for keeping this alive <3
Freelancer, Using it everyday ^^

**Comment by UnderDogg** [comment]
@TheGranadilla would you like to help us out? Doesn't matter in which area, we just need extra people.
Come find us on slack

**Comment by codyjbennett** [comment]
>  would you like to help us out? Doesn't matter in which area, we just need extra people. Come find us on slack

@UnderDogg I'd be up to help with some testing when there's a new version to play with. I don't have any experience with github or app development generally speaking... Also, over in slack there doesn't seem to be a lot of activity... Are there specific channels that the discussion is happening in? It seems that anything current is about IP_v1. IP_v2 or dev channels all are quiet. Thanks.

**Comment by UnderDogg** [comment]
I've set up a new discussion in the V2 channel on slack.
These are the channels:
- development => general development questions, like help with installing Laravel for V2, of course
- IPv1 => questions about V1
- IPv2 => discussions about V2, what do you need from V2, things like that

**Comment by a-kriya** [comment]
@UnderDogg How do I join the Slack org? I've been using IP for a few years now, and would like to contribute back. My experience is mainly with developing single-page apps with Vue, and Bootstrap (v4/5 -- I realize IP uses v3).

**Comment by codyjbennett** [comment]
@a-kriya here's the slack invite link: https://join.slack.com/t/invoiceplane/shared_invite/zt-sjirc9h2-952baR9rn4r8LyzRK9MveA

**Comment by virtiqa** [comment]
FYI all, I am working on a PR for PHP8.1 support, however PHP8.1 support requires an omnipay upgrade from v2 to v3 which might mean many online payment gateways will no longe be supported.

See this comparison of omnipay v2 and v3: https://github.com/thephpleague/omnipay under 'Payment Gateways'

 I think many of the v2 payment gateways are outdated anyway and not sure how many are used outside of the most popular ones like paypal and stripe.

**Comment by nielsdrost7** [comment]
@muddydev check out PR https://github.com/InvoicePlane/InvoicePlane/pull/862 for the PHP 8.1 Compatibility work

**Comment by nielsdrost7** [comment]
@muddydev Beta version released, see if it works out for you.

**Comment by onny** [comment]
Thank you @nielsdrost7 :) Could you please update the "compiled" release tarball of the 1.6-beta, the current release if outdated: https://github.com/InvoicePlane/InvoicePlane/releases/download/v1.6-beta/v1.5.11.zip
Note the file `v1.5.11.zip`

**Comment by nielsdrost7** [comment]
@onny that v1.5.11 file was my fault, I got rid of it.

**Comment by onny** [comment]
Could you provide a release tarball with precompiled assets like in the releases before? The v1.5.11.zip file contained the vendor directory and compiled assets from npm build. Manually building Invoiceplane is a bit tricky on NixOS so this release tarball would be very useful

**Comment by nielsdrost7** [comment]
Yes, working on it. It it ok, if it's a .zip file?
I've had some technical difficulties, so bare with me while I compile that file.

**Comment by onny** [comment]
zip file is fine :) thank you thats very helpful!

**Comment by nielsdrost7** [comment]
@onny Here is the .zip file: https://github.com/InvoicePlane/InvoicePlane/releases/download/v1.6-beta-1/v1.6-beta-1.zip however right now it has an `ip` directory in it.
Also, the filesize is a bit big (50MB towards 13MB last time).

If you want it changed, let me know.

**Comment by onny** [comment]
Thanks, updated our package https://github.com/NixOS/nixpkgs/pull/194059
Just need to fix the NixOS tests

**Comment by onny** [comment]
I'm further adding features to the Invoiceplane NixOS module, see the [example setup in the NixOS wiki](https://nixos.wiki/wiki/Invoiceplane).

The latest beta release tarball seems to miss some javascript dependencies. At least when I try to add a new invoice I get following errors in the JS console:
```
Uncaught ReferenceError: require is not defined
    <anonymous> http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
[dependencies.min.js:1:328591](http://localhost/assets/core/js/dependencies.min.js?v=1.5.12)
Uncaught ReferenceError: Dropzone is not defined
    <anonymous> http://localhost/index.php/clients/view/1#:33
[1:33:5](http://localhost/index.php/clients/view/1#)
Uncaught ReferenceError: ClipboardJS is not defined
    <anonymous> http://localhost/assets/core/js/scripts.min.js:1
    t http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
    e http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
    setTimeout handler*Deferred/then/c/< http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
    s http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
    fireWith http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
    fire http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
    s http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
    fireWith http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
    ready http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
    lt http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
    EventListener.handleEvent* http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
    <anonymous> http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
    <anonymous> http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
[scripts.min.js:1:2679](http://localhost/assets/core/js/scripts.min.js)
```
Not sure if this is a NixOS specific issue. I'm using the 1.6-beta release tarball but the logs above still shows the old version number

**Comment by onny** [comment]
> I'm further adding features to the Invoiceplane NixOS module, see the [example setup in the NixOS wiki](https://nixos.wiki/wiki/Invoiceplane).
> 
> The latest beta release tarball seems to miss some javascript dependencies. At least when I try to add a new invoice I get following errors in the JS console:
> 
> ```
> Uncaught ReferenceError: require is not defined
>     <anonymous> http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
> [dependencies.min.js:1:328591](http://localhost/assets/core/js/dependencies.min.js?v=1.5.12)
> Uncaught ReferenceError: Dropzone is not defined
>     <anonymous> http://localhost/index.php/clients/view/1#:33
> [1:33:5](http://localhost/index.php/clients/view/1#)
> Uncaught ReferenceError: ClipboardJS is not defined
>     <anonymous> http://localhost/assets/core/js/scripts.min.js:1
>     t http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
>     e http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
>     setTimeout handler*Deferred/then/c/< http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
>     s http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
>     fireWith http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
>     fire http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
>     s http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
>     fireWith http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
>     ready http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
>     lt http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
>     EventListener.handleEvent* http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
>     <anonymous> http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
>     <anonymous> http://localhost/assets/core/js/dependencies.min.js?v=1.5.12:1
> [scripts.min.js:1:2679](http://localhost/assets/core/js/scripts.min.js)
> ```
> 
> Not sure if this is a NixOS specific issue. I'm using the 1.6-beta release tarball but the logs above still shows the old version number

Issue is still present in 1.6-beta2 ( https://github.com/InvoicePlane/InvoicePlane/releases/download/v1.6-beta-2/v1.6-beta-2.zip ).
Is it possible to include the missing dependencies in the release tarball? In earlier releases everything necessary to use InvoicePlane was already included.

**Comment by nielsdrost7** [comment]
>> Is it possible to include the missing dependencies in the release tarball? In earlier releases everything necessary to use InvoicePlane was already included.

Yep, that's what gets added every time we create that extra .zip file.
It;s even worse: In the current `dependencies.min.js` in the .zip file, Dropzone is present:
![image](https://user-images.githubusercontent.com/47660417/201483482-bd8f1f89-d612-4764-b4f5-084187f06035.png)

I'll re-generate the files again, making *beta-3*.
If you can reproduce the error again, can you check that version that's after those files? I made it version 1.6 instead of 1.5.12 in these last 2 beta versions.

**Comment by onny** [comment]
Thank you so much for investigating 🙏

**Comment by nielsdrost7** [comment]
https://github.com/InvoicePlane/InvoicePlane/releases/tag/v1.6-beta-3 => (pray)

**Comment by onny** [comment]
Nice this fixed the issue, thank you.

Covered in https://github.com/NixOS/nixpkgs/pull/200936/commits for NixOS

**Comment by aksysict** [comment]
Hi guys i tried #831 and #858 but i cant get my invoiceplane to work with php 8.1 its an existing setup v1.5.11 can someone guide which steps needs to be taken? Thanks!!!

**Comment by nielsdrost7** [comment]
@aksysict which error are you getting? Do you have a screenshot?

**Comment by aksysict** [comment]
@nielsdrost7 thanks for the fast reply i follow.the file changes in #831 and  changed the same files with the new code lines. After that i change the php version from.7.4 to 8.1 on the hosting provider and i get only blank page. When i remove the new lines (dotenv) in index.php and set the old codes. Then it workes only dashboard. Invoices/clients/settings and other stuff does not work.

**Comment by nielsdrost7** [comment]
Ok, do me a favor: Open a new issue here or on the **forums**. Or find me on slack.
More users are going to run into this and I don't want it buried in this issue.

A blank page isn't good, but it's a PHP setting.
Then:
- open ipconfig.php
- remove the top line (about direct access)
- turn debug mode on

If you look in the `development` branch, those are all the changes you need.
There is a change in a package called phpdotdev.
A good solution would be to rename your ipconfig.php to `.env`, but let's consider that at the end.

**Comment by aksysict** [comment]
@nielsdrost7 i removed the first line in ipconfig.php -> <?php exit('No direct script access allowed'); ?>

i turned on the debug mode on google chrome see the screenshot attached. this is exact the same what happend with the code in ipconfig.php so nothing changes[
![error](https://user-images.githubusercontent.com/83404331/201535104-13c94254-03e8-43ff-ab90-194ec75ce5e6.png)
](url)

**Comment by aksysict** [comment]
@nielsdrost7 and if i change the ipconfig.php to ipconfig.env i get this error: The ipconfig.php file is missing! Please make a copy of the ipconfig.php.example file and rename it to ipconfig.php

**Comment by naui95** [comment]
Just in time for the PHP 7 retirement, the new version that supports PHP 8 is out https://github.com/InvoicePlane/InvoicePlane/releases/tag/v1.6.0
