### ISSUE TITLE
What's about the task module?

### ISSUE THREAD

**Issue by lefuturiste** [InvoicePlane/InvoicePlane#802]
Can we define a duration for each task and then compute the bill for a project by summing every task duration and multiplying by the hourly or daily rate? It's the core feature for a billing software that I'm looking for.

**Comment by clockwiseq** [comment]
We can most certainly document this as a request/enhancement and see if we can get someone to work on it.  Since our current focus is the new release with upgrades and bug fixes, I can't guarantee that we can get it into a sprint that will make it into that release.  Anyone is more than welcome though to grab it and work on it.

**Comment by UnderDogg** [comment]
So let me get this straight.
You have a task: Documentation.
You wrote 2 hours for it, somewhere.
Then you want to make your invoice.
You want to create that invoice for:
Documentation => 2 hours * (hourly rate for client)
or
Documentation => 2 hours * (hourly rate for project)

Is that what you want from the enhancement?

**Comment by lefuturiste** [comment]
@UnderDogg Yes that the basis
Being able to bill in hours and have a bill where each task is listed with the number of hours associated with it. 
Being able to do the same for quote would be a nice addition too.

**Comment by clockwiseq** [comment]
Not to name-drop here, but [HarvestApp ](https://www.getharvest.com)does that exact thing.  You have an area where you document hours worked with detailed notes of what you did and what project/task it was associated.  Then, when you are ready to bill those hours, you simply click "Bill for Hours" or something like that, and you are presented with a list of the hours worked that have not yet been billed and select them, then it generates a new invoice with those lines of work.  They even include a timer you can start/end when you begin work.

**Comment by UnderDogg** [comment]
I was thinking the exact same thing and the exact same app

**Comment by lefuturiste** [comment]
> I was thinking the exact same thing and the exact same app

Yes But is this app (Harvest) Free software? Can I self host it?

**Comment by clockwiseq** [comment]
> > I was thinking the exact same thing and the exact same app
> 
> Yes But is this app (Harvest) Free software? Can I self host it?

No, it's not free and we're not suggesting you use it.  We were referencing that app for an example of what needs to happen in this new feature if we decide to implement it.

**Comment by nielsdrost7** [comment]
A free app with similar functionality as Harvest is [Clockify](https://clockify.me) And it is free.
