### ISSUE TITLE
Add "Jobs" feature

### ISSUE THREAD

**Issue by onetrackmac** [InvoicePlane/InvoicePlane#808]
This is a great (and beautiful) app. Thanks for all the hard work!

However, it really lacks a "Jobs" feature, at least for my use. I deal with a small number of clients, but a lot of jobs per client. I need a way to create a list of jobs for each client, and then invoices (draws) for each job.

Thanks again.

**Comment by UnderDogg** [comment]
Thanks for the compliment.

For now.. I would start with Projects.
So ... let's say that you have 5 clients and all of them want an application
1) Create the clients, easy
2) Create Projects per client
3) Per project you can create tasks. Finish the tasks, then bill those finished tasks

**Comment by nielsdrost7** [comment]
@onetrackmac I'm closing this issue. For newer versions we'll look into something similar as you suggested, but ... `Jobs` is a reserved word, so we need to figure out a better name.
