### ISSUE TITLE
[ONLY Zugfred invoices] Client name is not escaped during PDF generation

### ISSUE THREAD

**Issue by Forceu** [InvoicePlane/InvoicePlane#809]
The client name is not escaped during PDF generation - which raises an error if the Client for example has an ampersand (&) in their name.

**Comment by UnderDogg** [comment]
@Forceu does your bug only occur in Zugferd invoices or also in regular invoices?
In case of regular invoices, can you apply your fix there too, please.
I saw your PR. If you can apply your fix in that PR, that would be great

**Comment by Forceu** [comment]
I assume it only happens with the Zugferd XML addition, as this was the only error that got raised during PDF generation. After the fix I was able to generate PDFs again.

There is a couple of other entries in the Zugferd library that aren't escaped, but I did not want to include them in this PR as I am not sure what consequences this could possible have without any proper testing.

**Comment by nielsdrost7** [comment]
Resolved with PR #810
