### ISSUE TITLE
FEATURE - Stripe Integration Outdated

### ISSUE THREAD

**Issue by clockwiseq** [InvoicePlane/InvoicePlane#814]
Stripe integration is outdated, I got error. Please update it according to their docs

_Originally posted by @anondev-sudo in https://github.com/InvoicePlane/InvoicePlane/issues/307#issuecomment-1143483550_

**Comment by anondev-sudo** [comment]
![image](https://user-images.githubusercontent.com/85408287/171421363-7403b0a5-3392-4693-8af4-e6db79a660f2.png)

After entering cc details and clicking submit - 
![image](https://user-images.githubusercontent.com/85408287/171422105-dca1404e-500d-47d8-8b01-bffb36c117bf.png)

**Comment by anondev-sudo** [comment]
Docs: https://stripe.com/docs/payments/quickstart

**Comment by anondev-sudo** [comment]
Also please check #757

**Comment by clockwiseq** [comment]
Perfect, thanks!

**Comment by anondev-sudo** [comment]
I'm sorry but I don't have any skills with php - I code in NodeJS.

**Comment by nielsdrost7** [comment]
See PR #816 I'm closing this issue.
