### ISSUE TITLE
[Feature Request] Shoppy.gg payment gateway

### ISSUE THREAD

**Issue by anondev-sudo** [InvoicePlane/InvoicePlane#815]
Online payments are outdated, paypal and stripe is not working for me.

Please add shoppy.gg option for accepting payments. 
> Shoppy Pay provides several online payment methods to implement a real-time checkout experience for any e-commerce platform supporting a range of payment methods in one place.

> For each payment, a unique URL will be returned. The customer will have to be redirected to the URL in order to access the checkout page

After you get the payment url, redirect the user there. You can pass **webhook_urls** array parameter, shoppy will make POST request with details there once it's paid. You should make php file (webhook) where it will listen for requests from shoppy and mark invoice as paid when it was received (you can pass invoice number as title and you don't need to save payment link in database, every time user clicks on it, new can be generated)

**Comment by anondev-sudo** [comment]
Shoppy supports paypal, stripe and crypto (crypto with 5% processing fee)

**Comment by nielsdrost7** [comment]
@anondev-sudo thank you for your issue.
Feel free to create your pull-request against the `development` branch, so we can take a look at it

**Comment by merwin619** [comment]
my shop recieved 1o orders which are bought by clients, but no amount has been paid from shoppy to my wallet , no proper response from them , all are btc transactions, more than $750,
is my account is hacked or shoppy.gg has some flaw with them

**Comment by naui95** [comment]
I removed the docs link from the original issue because the domain is parked on a strange website. The https://shoppy.gg/ website also is linking that strange link for the docs. I personally do not know the gateway; are we sure that the shoppy service is trustworthy?

**Comment by nielsdrost7** [comment]
ok, that's it.
@merwin619 please post your request on the community forums so we can dig into if this is something we need. I think I asked you a year ago?

The strange url that naui95 removed was the drop. We don't need strange urls in our issues.

**Comment by anondev-sudo** [comment]
Was it added?

**Comment by nielsdrost7** [comment]
Hey @anondev-sudo shoppy.gg was not added to InvoicePlane.
If you want, you can still do that and make a pull-request.

If I keep looking at strange urls, strange urls for documentation, then I'd rather only add stripe and PayPal and hope that shoppy.gg can work with that.

Would you mind making a pull-request for that?
Maybe 2 separate ones, that would be better.

**Comment by anondev-sudo** [comment]
Paypal and stripe should be implemented, the current integrations are not working

**Comment by anondev-sudo** [comment]
you can reopen this issue

**Comment by anondev-sudo** [comment]
why it was closed as completed when it was not added

**Comment by nielsdrost7** [comment]
> Paypal and stripe should be implemented, the current integrations are not working

Reopened for the pull-requests to implement Paypal and Stripe.
Check this page:
https://github.com/thephpleague/omnipay
If the libraries are available.

@anondev-sudo could you make those pull-requests?

**Comment by naui95** [comment]
> Paypal and stripe should be implemented, the current integrations are not working

Dear @anondev-sudo we are implementing PayPal and Stripe (for paypal see #757 and for stripe #1006); the PR to follow the development is #1046 

As for `shoppy.gg` (this issue is only about this payment gateway), have you ever used it? I personally don't know the gateway and as far as I could understand from some research (mainly reddit) it isn't really trustworthy. Their documentation is also not available online and the modules they provide from their website have not been updated for 4 years now. If you believe that PayPal and Stripe (and Mollie) are enough, I would suggest to follow through with @nielsdrost7 proposal to close this issue as a feature we are not going to implement.
