### ISSUE TITLE
User Types & Permissions

### ISSUE THREAD

**Issue by JohnDS1** [InvoicePlane/InvoicePlane#817]
Have the ability to create User Types with specific permissions such as:
Creating Quotes
Editing Quotes
Creating Invoices
Editing Invoices
Creating Products
Editing Products
and many more

**Comment by nielsdrost7** [comment]
Hi @JohnDS1,
Thank you for the issue.
InvoicePlane does not have a permissions system.
It only has user types.

It's a good feature request for a future version.

**Comment by nielsdrost7** [comment]
I'm closing this issue
