### ISSUE TITLE
Issues with SSL and InvoicePlane in CapRover

### ISSUE THREAD

**Issue by walderfranco** [InvoicePlane/InvoicePlane#820]
I'm using CapRover, I have InvoicePlane installed and SSL enabled, the problem is that when you enable the option: "Force HTTPS by redirect all HTTP traffic to HTTPS" InvoicePlane crashes.
The error is 502, CapRover blue screen.

**Comment by nielsdrost7** [comment]
I'm sorry, but what the hell is CapRover?
What is it saying in the error logs?

If you show the errors, that would help.
When you post the logs, don't post personal information like paths to files.

**Comment by nielsdrost7** [comment]
Closing

**Comment by nileshtrivedi** [comment]
Looks like InvoicePlane needs to serve protocol-relative URLs: https://github.com/caprover/caprover/issues/1454

**Comment by LuchoAGN** [comment]
InvoicePlane continues to have problems with CapRover, it continues to use 'http' instead of 'https' and generates a mix-up error.

**Comment by nileshtrivedi** [comment]
@nielsdrost7 Please see my comment above and the discussion in https://github.com/caprover/caprover/issues/1454. This is not a Caprover-specific issue but something that InvoicePlane needs to fix. It should not assume whether it's being served over HTTP or HTTPS. The fix is simply to use protocol-relative URLs for assets etc.

**Comment by nielsdrost7** [comment]
@nileshtrivedi go ahead and make your solution. You can even make it on a branch in the InvoicePlane repository if you like.

This is a search for 'base_url' which is where you place the protocol.
It's part of a configuration offered by CodeIgniter version 3.

https://github.com/search?q=repo%3AInvoicePlane%2FInvoicePlane+base_url&type=code

Alternative is to place `https` in the `IP_URL` in the `ipconfig.php` file.

As far as I know if you use `https` in your `IP_URL` you won't have any problems with mixed http and https
