### ISSUE TITLE
MySql Error 'connection refused' now and then, when i try to log in

### ISSUE THREAD

**Issue by JohnDS1** [InvoicePlane/InvoicePlane#825]
For the past week I have been getting this error every now and then while using invoice plane. I am not sure how to fix it.

**Comment by JohnDS1** [comment]
@nielsdrost7 Hi, I spoke to my hosting company and they said there is nothing wrong on their side. 

I really need help sorting this out as it's making it really hard to use the application, every second thing I do on the application shows the error.

I went to see the logs of the invoice plane and this is what they are:

ERROR - 2022-07-26 08:42:08 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 08:42:08 --> Unable to connect to the database
ERROR - 2022-07-26 08:42:08 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 09:02:20 --> 404 Page Not Found: /index
ERROR - 2022-07-26 09:12:23 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 09:12:23 --> Unable to connect to the database
ERROR - 2022-07-26 09:12:23 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 09:20:04 --> 404 Page Not Found: /index
ERROR - 2022-07-26 09:26:31 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 09:26:31 --> Unable to connect to the database
ERROR - 2022-07-26 09:26:31 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 09:26:42 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 09:26:42 --> Unable to connect to the database
ERROR - 2022-07-26 09:26:42 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 09:26:44 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 09:26:44 --> Unable to connect to the database
ERROR - 2022-07-26 09:26:44 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 09:26:52 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 09:26:52 --> Unable to connect to the database
ERROR - 2022-07-26 09:26:52 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 09:26:56 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 09:26:56 --> Unable to connect to the database
ERROR - 2022-07-26 09:26:56 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 09:27:03 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 09:27:03 --> Unable to connect to the database
ERROR - 2022-07-26 09:27:03 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 09:27:07 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 09:27:07 --> Unable to connect to the database
ERROR - 2022-07-26 09:27:07 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 09:27:08 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 09:27:08 --> Unable to connect to the database
ERROR - 2022-07-26 09:27:08 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 09:27:09 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 09:27:09 --> Unable to connect to the database
ERROR - 2022-07-26 09:27:09 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 09:27:10 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 09:27:10 --> Unable to connect to the database
ERROR - 2022-07-26 09:27:10 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 09:27:18 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 09:27:18 --> Unable to connect to the database
ERROR - 2022-07-26 09:27:18 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 09:27:20 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 09:27:20 --> Unable to connect to the database
ERROR - 2022-07-26 09:27:20 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 09:27:37 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 09:27:37 --> Unable to connect to the database
ERROR - 2022-07-26 09:27:37 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 09:27:39 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 09:27:39 --> Unable to connect to the database
ERROR - 2022-07-26 09:27:39 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 09:27:39 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 09:27:39 --> Unable to connect to the database
ERROR - 2022-07-26 09:27:39 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 09:27:40 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 09:27:40 --> Unable to connect to the database
ERROR - 2022-07-26 09:27:40 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 11:05:25 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 11:05:25 --> Unable to connect to the database
ERROR - 2022-07-26 11:05:25 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 11:05:26 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 11:05:26 --> Unable to connect to the database
ERROR - 2022-07-26 11:05:26 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 11:05:28 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 11:05:28 --> Unable to connect to the database
ERROR - 2022-07-26 11:05:28 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 11:05:31 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 11:05:31 --> Unable to connect to the database
ERROR - 2022-07-26 11:05:31 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 14:34:30 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 14:34:30 --> Unable to connect to the database
ERROR - 2022-07-26 14:34:30 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 14:34:30 --> 404 Page Not Found: /index
ERROR - 2022-07-26 14:41:07 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 14:41:07 --> Unable to connect to the database
ERROR - 2022-07-26 14:41:07 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 14:41:10 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 14:41:10 --> Unable to connect to the database
ERROR - 2022-07-26 14:41:10 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 14:41:11 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 14:41:11 --> Unable to connect to the database
ERROR - 2022-07-26 14:41:11 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 14:41:12 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 14:41:12 --> Unable to connect to the database
ERROR - 2022-07-26 14:41:12 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 14:41:12 --> 404 Page Not Found: /index
ERROR - 2022-07-26 15:01:03 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 15:01:03 --> Unable to connect to the database
ERROR - 2022-07-26 15:01:03 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 15:01:03 --> 404 Page Not Found: /index
ERROR - 2022-07-26 15:01:07 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 15:01:07 --> Unable to connect to the database
ERROR - 2022-07-26 15:01:07 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 15:01:08 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 15:01:08 --> Unable to connect to the database
ERROR - 2022-07-26 15:01:08 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 15:02:27 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 15:02:27 --> Unable to connect to the database
ERROR - 2022-07-26 15:02:27 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 15:02:29 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 15:02:29 --> Unable to connect to the database
ERROR - 2022-07-26 15:02:29 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 15:02:30 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 15:02:30 --> Unable to connect to the database
ERROR - 2022-07-26 15:02:30 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570
ERROR - 2022-07-26 15:02:33 --> Severity: Warning --> mysqli::real_connect(): (HY000/2002): Connection refused MY_DOMAIN/vendor/codeigniter/framework/system/database/drivers/mysqli/mysqli_driver.php 203
ERROR - 2022-07-26 15:02:33 --> Unable to connect to the database
ERROR - 2022-07-26 15:02:33 --> Severity: Warning --> Cannot modify header information - headers already sent by (output started at MY_DOMAIN/vendor/codeigniter/framework/system/core/Exceptions.php:271) MY_DOMAIN/vendor/codeigniter/framework/system/core/Common.php 570

**Comment by nielsdrost7** [comment]
I cut out the logs for you.

Suggestion is to get a different host.
When a connection to the database drops 'now and then', it's time to ask a different host if they can host the application for you.

**Comment by nielsdrost7** [comment]
Closing
