### ISSUE TITLE
[Use invoiceplane.org instead] website invoiceplane.com does not load

### ISSUE THREAD

**Issue by stapelberg** [InvoicePlane/InvoicePlane#826]
Not sure if you’re already aware, but I figured I’d file an issue in case you’re not.

When I try to open invoiceplane.com (or wiki.invoiceplane.com) in my browser, I see a CloudFlare error page, stating: Error 522 Ray ID: 72b9e022fe10bb3d • 2022-07-16 09:58:17 UTC: Connection timed out

This has been the case since at least Thursday ≈18:00 for me

**Comment by nielsdrost7** [comment]
Hi @stapelberg thank you for your issue.
We are aware of the problem and working on a fix at the moment.

Normally I would have advised to go to invoiceplane**.org**, but on that site the Wiki is disabled.

**Comment by nielsdrost7** [comment]
Closing. invoiceplane.com is back up and running (forums are missing for now, though)
