### ISSUE TITLE
[PHP 8?] OneClick | Softaculous Install Error

### ISSUE THREAD

**Issue by Zanrose** [InvoicePlane/InvoicePlane#828]
Hi Team!

I have just installed this application on my web server however I am getting lots of error after install.

I have no been able to even log into the application. Could you please point me in the right direction.

The app is installed here: https://quotes.jackcameron.com.au.

This is my first ever issue so please let me know if you need more information.

**Comment by nielsdrost7** [comment]
Most likely you have installed it on a server with PHP 8.
InvoicePlane isn't PHP 8 compatible, yet.

**Comment by nielsdrost7** [comment]
Closing
