### ISSUE TITLE
Custom Tax option and Payment Gateway

### ISSUE THREAD

**Issue by RitZz48** [InvoicePlane/InvoicePlane#829]
Hey, In my country Tax's are applicable under what's called GST, which in my Case will be flat 18%. Can I setup this custom tax option? 

Also, can I implement my own Payment Gateway? Most of the options provided doesn't work in my country.

**Comment by nielsdrost7** [comment]
> In my country Tax's are applicable under what's called GST, which in my Case will be flat 18%

Well... when you set your taxes in the settings, you can add whichever percentage you want.

> can I implement my own Payment Gateway
Sure you can, no problem there.

**Comment by nielsdrost7** [comment]
Closing
