### ISSUE TITLE
How do I change the Incremental Invoice Number

### ISSUE THREAD

**Issue by Zanrose** [InvoicePlane/InvoicePlane#833]
Hi Team!

How do I change the Incremental Invoice Number?

Ver: 1.5.11

**Comment by Zanrose** [comment]
or if you can let me know where that number is generated in PHP Database or files that would be great as well <3

**Comment by nielsdrost7** [comment]
@Zanrose https://wiki.invoiceplane.com/en/1.5/settings/invoice-groups => you can set the `Next ID` and that's the next invoice number you're looking for.
The table is called `invoice_groups`, but you can better do it using the interface.

Hope it helps
