### ISSUE TITLE
Error with the HTTPS

### ISSUE THREAD

**Issue by Doodke3** [InvoicePlane/InvoicePlane#835]
First, if I don't use HTTPS, the Clients tab won't work, and it's auto redirecting to HTTPS://
Then, if I use HTTPS, some CSS won't work with the error "This request has been blocked; the content must be served over HTTPS."

(The CSS won't work because it's HTTPS)

What do I do?
(Version 1.5.11)

**Comment by nielsdrost7** [comment]
Can you reproduce this locally on your own dev machine?
Is your server using Apache?
How is the .htaccess file looking?

You should try and remove that force to redirect part. Most likely in the .htaccess file

Even though https is great, the forcing redirect to https is the cause of your problem.

Also this part is not good:
> This request has been blocked; the content must be served over HTTPS

**Comment by Doodke3** [comment]
Sorry for the delay, 
How do I change the CSS to accept HTTPS CSS?
Like what do I add? I tried to search on google but the site is down...

Thanks!

**Comment by nielsdrost7** [comment]
It's a difficult rabbit hole to get in to.
I don't think you'll find anything about your question on the forums.

You can better attempt to answer your question in general then to pinpoint it on InvoicePlane.

Normally you don't need to change anything in CSS to handle https.
You want to serve a site: https://my-personal-site.com and on that site you'll have .css files.
In this case they're located in for example /assets/dist/css/app.css
It should show proper css.

Look into your Chrome dev tools if you see strange things and then Google for those strange things.

**Comment by Doodke3** [comment]
Mixed Content: The page at 'https://my-site.com/index.php/guest/view/invoice/xHboy5BKTCwqYO9uMQ6IljcPinWFrV8z' was loaded over HTTPS, but requested an insecure stylesheet 'http://my-site.com/assets/core/css/custom.css'. This request has been blocked; the content must be served over HTTPS.


This is what I get when I'm using HTTPS

**Comment by nielsdrost7** [comment]
Copy / paste your .htaccess file In this issue

**Comment by Doodke3** [comment]
## Run InvoicePlane in a subfolder
## If you are using a subfolder please remove the hash in front of the line ‘#RewriteBase /subfolder’
## and replace ‘subfolder’ with the actual name of your folder, i.e. ‘RewriteBase /invoices’

<IfModule mod_rewrite.c>

  RewriteEngine On
  #RewriteBase /subfolder
  RewriteRule ^index\.php$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.php [L]

  ## Remove the hash in front of the following two lines if you want to force HTTPS
  #RewriteCond %{HTTPS} off
  #RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]

</IfModule>

**Comment by Doodke3** [comment]
I added the "s" to the HTTP that connected the CSS to the page, and it worked, 
How do change that permanently?

Thanks!

**Comment by Doodke3** [comment]
So, I found this line:

`link href="<?php echo base_url(); ?>assets/<?php echo get_setting('system_theme', 'invoiceplane'); ?>/css/style.css" rel="stylesheet">`

Where is base_url set?

**Comment by nielsdrost7** [comment]
> Where is base_url set?
Most likely in ipconfig.php

**Comment by Doodke3** [comment]
oh wow thank you, i changed the http to https

thanks!!
