### ISSUE TITLE
MySQL 8.0 breaks on fresh install

### ISSUE THREAD

**Issue by Oxymoron290** [InvoicePlane/InvoicePlane#838]
crashes with Error Code: 1525. Incorrect DATE value: '000-00-00'.

A quick solution is to add the [ALLOW_INVALID_DATES](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_allow_invalid_dates) to the mysql config.

## This is a workaround

On the mysql database server, `sudo nano /etc/mysql/my.cnf` and add the following lines to the bottom of the file:

```
[mysqld]
sql-mode = "allow_invalid_dates"
```

then restart the mysql server and it should work.

## A more permanent solution

This project should be made compatible with a default Mysql 8.0 installation or remove the instructions that it is compatible with all version of mysql above 7.0

**Comment by nielsdrost7** [comment]
Hi,

Thank you for your issue.
You are Correct with the errors in combination with MySQL 8.x

MySQL 8.x and beyond is unsupported.

**Mariadb** is supported, however.
