### ISSUE TITLE
using old mpdf version sets temp directory to /vendor/mpdf/temp

### ISSUE THREAD

**Issue by Oxymoron290** [InvoicePlane/InvoicePlane#839]
The setup currently checks if various directories are writable. However when generating a PDF of a quote, it is expected that `vendor/mpdf/mpdf/tmp` be writeable and the setup script does not validate this.

**Comment by nielsdrost7** [comment]
Strange. In a basic docker setup I haven't had these problems.
Isn't this an issue like 'it works on my machine?

Are you trying this locally or on a server?

**Comment by Oxymoron290** [comment]
This is a fresh Debian 11 install with all artifacts copied over as root and the specified owners `chown`ed to `www-data:www-data`

**Comment by nielsdrost7** [comment]
Ok, that's great. It's just really strange, because any docker setup (usually alpine) doesn't have a problem

**Comment by Oxymoron290** [comment]
> Looks like you need a newer version of mpdf: `composer require mpdf/mpdf (version)`

That could be, but I did not specifically install it. It must have either been installed as part of a base package for debian, as part of the install for apache2, or as part of the install for php (7.4)

**Comment by Oxymoron290** [comment]
> > Looks like you need a newer version of mpdf: `composer require mpdf/mpdf (version)`
> 
> That could be, but I did not specifically install it. It must have either been installed as part of a base package for debian, as part of the install for apache2, or as part of the install for php (7.4)

Oh I said this assuming mpdf was a php extension, I didn't realize it was a library. Then this installation came as part of the .zip archive download from the invoiceplane website.

**Comment by nielsdrost7** [comment]
Right, so you're on your debian server, in your InvoicePlane directory and execute that composer command to get your newer mpdf version.

Current mpdf version, that's in the composer, in the .zip file that you downloaded is an older version and yes, looking at the Google results, it points to a temp directory in your vendor directory.

mpdf resolved that and made a newer version.
So it's either waiting for a newer version of InvoicePlane or running that composer command

**Comment by Oxymoron290** [comment]
perfect! Thank you!
