### ISSUE TITLE
Quote PDF displays customer address incorrectly

### ISSUE THREAD

**Issue by Oxymoron290** [InvoicePlane/InvoicePlane#840]
When generating a PDF of a quote, the Addresses "state" field is displayed twice on the PDF

The below image shows an example. On the left is with the state field in the client's address blank so that it doesn't display at all. On the right shows a client with the state field populated in the client's profile.

![image](https://user-images.githubusercontent.com/2234419/185778575-e68d8900-a764-45be-8341-23ab7dc82ad1.png)

**Comment by Verony-makesIT** [comment]
@Oxymoron290:
It seems that the default pdf quote template contains an error.
If you use the _"state field_" then it will be shown twice in the quote pdf. 
To solve this quickly, you should make a copy of the template file yourself and then in **_your template file_** **delete line 46 through line 48**.
```
if ($quote->client_state) {
    echo '<div>' . htmlsc($quote->client_state) . '</div>';
}
```

> Then don't forget to also modify the name of your new PDF template file in "Settings - Quote - Quote Templates".

The default IP version will have to be adjusted accordingly.
@nielsdrost7: Can you assign this issue to me?
