### ISSUE TITLE
State of the Development

### ISSUE THREAD

**Issue by xeruf** [InvoicePlane/InvoicePlane#851]
The initial impression is rather stale:
Last commit to master and last release two years ago, demo unavailable on the website.
I was about to shrug this project off as dead until I stumbled upon active issue discussions and mentions of a version 2.
Then I had to rummage through the stale branches (including "2.0") to find what is actually going on.

So please, for your own good:
- prominently mention version 2 is in development (on readme and website), with a rough roadmap
- clean up stale branches
- consider bringing the demo back online

**Comment by nielsdrost7** [comment]
Thanks for bringing this up.
The development is done in the `development` branch.
As you can see, there are a couple of active Pull-requests.

One of the Pull-requests is for PHP8 compatibility.
As soon as that's done, we'll merge that back into the master branch.

The talks about "version 2" are done on our Slack channels.

Once the PHP8 version is released, we'll clean up the old branches.

**Comment by xeruf** [comment]
oh, and for the demo linked in the repo I have no idea how to login, especially since it is not in english

**Comment by nielsdrost7** [comment]
Check out https://github.com/InvoicePlane/InvoicePlane/pull/862, there's your recent development
