### ISSUE TITLE
Updated Stripe integration does not receive token

### ISSUE THREAD

**Issue by naui95** [InvoicePlane/InvoicePlane#852]
> New stripe integration currently not working

**How to reproduce**:

1. Activate stripe as a payment method
2. Create invoice
3. Go to invoice guest page
4. Pay with stripe
5. Page just refreshes

**Symptoms**:

- The console logs an empty token

**To do**

- [x] fix component
- [x] implement better error handling

**Comment by nielsdrost7** [comment]
PR #854 closes this issue.
Great job!
