### ISSUE TITLE
Import component does not provide upload field

### ISSUE THREAD

**Issue by naui95** [InvoicePlane/InvoicePlane#853]
**How to reproduce**:

1. Login as admin
2. Go to import section
3. Create new import

**Comment by naui95** [comment]
Closing issue. Works as designed.
"The files to import must be located in your uploads/import folder." (https://wiki.invoiceplane.org/en/1.5/system/importing-data)

**Comment by nielsdrost7** [comment]
Holy shit!
Thanks for the solution, man!
