### ISSUE TITLE
PHP8 compatibility branch: phpdotenv is too new

### ISSUE THREAD

**Issue by nielsdrost7** [InvoicePlane/InvoicePlane#855]
Solution: downgrade your Dotenv version to this:
`"vlucas/phpdotenv": "^3.4.0"`
Alternate solution:
phpdotenv changed the way it's being initiated in its 5.4 version:
```
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__, 'custom-config-filename);
$dotenv->load();
```

Url: https://github.com/vlucas/phpdotenv

**Comment by naui95** [comment]
@nielsdrost7 phpdotenv `3.4.0` does not seem to be PHP 8 compatible (see: https://github.com/vlucas/phpdotenv/releases?page=3). I would suggest changing the initialization in out code. Should not be too much trouble. We could start making a branch in our repo with the pull request (#831 ) what do you say?

**Comment by nielsdrost7** [comment]
I agree, that's what I wanted to talk about
