### ISSUE TITLE
Option to enter discount

### ISSUE THREAD

**Issue by Kovah** [InvoicePlane/InvoicePlane#86]
> Source: [forum post](https://community.invoiceplane.com/t/discount-option/78)

**Comment by WiraSoenaryo** [comment]
Would love to have it too...
Discount pretty uselfull on invoicing..

**Comment by 3zzy** [comment]
Ah, I installed it and everything ... No discount feature.. Deleted :(

**Comment by Kovah** [comment]
@3zzy Its correct that there is no discount option but you can add a discount as an article with a negative amount. I'm doing this since the first day of using InvoicePlane.

**Comment by 3zzy** [comment]
Yes, but most times I need to provide discount per product, not on the overall purchase which is not possible. :(
