### ISSUE TITLE
i get this error when try to extract Arabic pdf: Cannot find TTF TrueType font file "XB Riyaz.ttf" in configured font directories 

### ISSUE THREAD

**Issue by LuckyIdea2** [InvoicePlane/InvoicePlane#871]
An uncaught Exception was encountered
Type: Mpdf\MpdfException

Message: Cannot find TTF TrueType font file "XB Riyaz.ttf" in configured font directories.

**Comment by nielsdrost7** [comment]
Check out the forum post about it: https://community.invoiceplane.com/t/topic/9396

When it says `Cannot find TTF TrueType font file "XB Riyaz.ttf" in configured font directories` what would you think you would need to do?
