### ISSUE TITLE
PDF generation error due to & in customers title

### ISSUE THREAD

**Issue by klodeckl** [InvoicePlane/InvoicePlane#872]
If the customer name contains a & character, PDF generation of invoices fails.

**Comment by naui95** [comment]
Hi @klodeckl thank you for bringing up the bug. I could reproduce it and will push a fix for the next (upcoming) release.

**Comment by klodeckl** [comment]
Could you please link the pull request here? (I think I would need a fix before the next release)

**Comment by naui95** [comment]
Problem does not appear in new release . It is probably due to the fact that the new IP-release uses an updated version of mpdf.

**Comment by nielsdrost7** [comment]
@klodeckl The new release is going to be soon, real soon.
Can you live with a beta version?

**Comment by klodeckl** [comment]
Yes. Thank you!
