### ISSUE TITLE
[Mcrypt extension missing] Softaculous Install Error - Required PHP extension not found : mcrypt

### ISSUE THREAD

**Issue by Webtems** [InvoicePlane/InvoicePlane#877]
Hello, while trying to install InvoicePlane via Softaculous, I'm getting the following error:

  The following errors were found :

Required PHP extension not found : mcrypt

Any help would be appreciated.

**Comment by clochenberg09** [comment]
Enable the mcrypt extension under your php settings

**Comment by clochenberg09** [comment]
In your c-panel under php version
![mcrypt](https://user-images.githubusercontent.com/117229897/199345826-e8af7be4-9485-43aa-819a-d37b615d8a7c.png)
