### ISSUE TITLE
Uncaught Dotenv\Exception\InvalidFileException: Failed to parse dotenv file

### ISSUE THREAD

**Issue by christoferd** [InvoicePlane/InvoicePlane#894]
Uncaught Dotenv\Exception\InvalidFileException: Failed to parse dotenv file. Encountered an invalid name at [<?php exit('No direct script access allowed'); ?>]

## Expected Behavior
Expect the app to just run without any errors.

## Current Behavior
Instead of the page loading, it shows HTTP ERROR 500

## Possible Solution
Better install instructions.

## Steps to Reproduce
1. Download v1.6.0 from the suggested location (linked in the documentation)
2. Extract to a _folder_
3. Create config.php by copying the example file. Edit URL to PHP local server URL
4. Open terminal in _folder_
5. Start a PHP server with > php -S `127.0.0.1:8000`
6. Navigate to http:... your local URL
7. ... notice the 500 error in the browser, and see detailed error stacktrace in terminal

## Context (Environment)
Is an apache server a requirement?
There are no details of requirements in the read.me

## Detailed Description
Install instructions need a lot of help!

## Failure Logs
[Mon Dec  5 18:34:14 2022] 127.0.0.1:49717 [500]: GET / - Uncaught Dotenv\Exception\InvalidFileException: Failed to parse dotenv file. Encountered an invalid name at [<?php exit('No direct script access allowed'); ?>]. in C:\www\Mindflow\invoice.mindflow.com.au\www\vendor\vlucas\phpdotenv\src\Parser\Parser.php:30
Stack trace:
#0 C:\www\Mindflow\invoice.mindflow.com.au\www\vendor\graham-campbell\result-type\src\Error.php(118): Dotenv\Parser\Parser::Dotenv\Parser\{closure}()
#1 C:\www\Mindflow\invoice.mindflow.com.au\www\vendor\vlucas\phpdotenv\src\Parser\Parser.php(31): GrahamCampbell\ResultType\Error->mapError()
#2 C:\www\Mindflow\invoice.mindflow.com.au\www\vendor\vlucas\phpdotenv\src\Dotenv.php(222): Dotenv\Parser\Parser->parse()
#3 C:\www\Mindflow\invoice.mindflow.com.au\www\index.php(20): Dotenv\Dotenv->load()
#4 {main}
  thrown in C:\www\Mindflow\invoice.mindflow.com.au\www\vendor\vlucas\phpdotenv\src\Parser\Parser.php on line 30
[Mon Dec  5 18:34:14 2022] 127.0.0.1:49717 Closing
[Mon Dec  5 18:34:15 2022] 127.0.0.1:49725 Accepted
[Mon Dec  5 18:34:15 2022] 127.0.0.1:49725 [404]: GET /flutter_service_worker.js?v=5.5.24 - No such file or directory
[Mon Dec  5 18:34:15 2022] 127.0.0.1:49725 Closing

**Comment by nielsdrost7** [comment]
@

**Comment by morj-uio** [comment]
Regarding the top line in ipconfig.php: 
I commented it out with a # instead, so the dotenv parser just ignores it. The php code (exit function) still remains functional and may be important for security.

**Comment by christoferd** [comment]
This from docs certainly helps "Breaking changes InvoicePlane 1.6 is based (as its versions before) on CodeIgniter which officially still **does not support PHP 8.1.**"

I was doing a fresh install, the fresh install instructions should recommend "revising Update Instructions." or something like that.

Min - Max server requirements would also help.

PS: I removed links in original post.
My issue is solved now as I was looking to migrate to a server running 8.1
I will migrate to a different server instead where I can control the PHP version.

**Comment by nielsdrost7** [comment]
@christoferd thanks for the update. Glad it's working now.
We'll update the documentation as soon as we can.
