### ISSUE TITLE
[Feature Request] Option to Initiate Terms (Due Date) When Sending Invoice - Suggested by Joey D'Anna

### ISSUE THREAD

**Issue by clockwiseq** [InvoicePlane/InvoicePlane#895]
## Expected Behavior
It would be helpful if there was an option (System Setting) to override the default behavior of calculating and setting the invoice and due dates (given a selected term) and to give the user the ability to reset these dates after the invoice is first sent.  So, if I create an invoice in 12/01/2022 and then leave it in a Draft status, the due date is not calculated nor stored.  When I send the invoice, it might be 12/06/2022, so the invoice date should reflect the current date and then calculate the due date based on today's date.  Again, some might not want this behavior, but I know a few users who would benefit from this.

## Current Behavior
When a new invoice is created and is in Draft status, the invoice date is automatically set for today's date which in turn automatically calculates the due date based on the term.  When you send an invoice, it might be after the date it was created, so the due date is not necessarily "fair" to the customer.

## Possible Solution
I feel that a System Setting is in order here and what could happen is have a switch to say something like "Reset Invoice and Due Date Upon Send".  By enabling this switch, it would change the invoice date to the current date when sending the invoice to the customer and recalculate the due date based on the selected terms.  Another option would be to make it standard to reset the invoice date to the current date when changing the status to anything but Draft _(potentially add a new invoice status)_.

## Steps to Reproduce
This is not a bug, but an issue for sure that requires the user to modify the invoice and due dates every time an invoice is sent.
1.  Create an invoice on one date (say 12/06/2022)
2.  Modify the invoice on another day (say 12/07/2022) 
3.  Send the invoice

## Context (Environment)
The overall issue is that when creating an invoice, the purpose of it being in a draft status is just to be able to work on the invoice.  Once the invoice is ready or done, that might not be the day that you first created the invoice.  When you send the invoice at this point, the invoice and due dates are skewed and have to be manually changed.

## Detailed Description
I am proposing is a change in the functionality of the setting and calculation of the invoice/due dates to only be set or changed upon changing the status from Draft.  Whether that be via changing it for everyone or making it an option in System Settings.  Doesn't matter to me, but would like feedback from the community to get their opinion on which they prefer.

## Possible Implementation
See Possible Solution above.

**Comment by nielsdrost7** [comment]
I'm sorry, I need to double check this. I'll close it after it's checked

**Comment by Verony-makesIT** [comment]
No problem. I thought everything was fine and then closed this issue.

**Comment by nielsdrost7** [comment]
There was a PR, #924 that introduced a bug, but it was rectified in #928:
https://github.com/InvoicePlane/InvoicePlane/pull/928
Both are in the `development` branch, which means the rectification of the bug will make it to version 1.6.2

**Comment by naui95** [comment]
seems to be fixed and ready to go (see https://github.com/InvoicePlane/InvoicePlane/issues/895#issuecomment-2380594372). Closing issue.
