### ISSUE TITLE
Possible XSS vulnerabilities

### ISSUE THREAD

**Issue by enferas** [InvoicePlane/InvoicePlane#902]
Edit:

Security report sent by email.

**Comment by johnfoley** [comment]
Thanks for your mail. The studio is closed from Thursday 22 Dec until Tuesday 10 January 2023. 

During that time emails will be monitored less frequently than usual. If you require an immediate response that is not a problem – please text one of the partners or resend your mail to ***@***.*** 

Merry Christmas, happy new year, peace on earth, mercy mild.
