### ISSUE TITLE
Required Fields Check

### ISSUE THREAD

**Issue by gklimm** [InvoicePlane/InvoicePlane#911]
## Expected Behavior

The software should point out user errors without running into an exception

## Current Behavior

Throw an exception

## Possible Solution

In HTML5 the attribute "required" in the form?

## Steps to Reproduce

1. Paymetns
2. Enter Payment
3. Leave amount blank or erase the date
4. Click "Save"

## Possible Implementation

put the attribute "required" on the input fields like "payment_date" and "payment_amount", because without this data, saving makes no sense

## Failure Logs

A PHP Error was encountered
Severity: Warning

Message: Undefined property: CI::$mdl_payment_custom

Filename: MX/Controller.php

Line Number: 64

Backtrace:

File: /var/www/ip/application/third_party/MX/Controller.php
Line: 64
Function: _error_handler

File: /var/www/ip/application/modules/payments/controllers/Payments.php
Line: 115
Function: __get

File: /var/www/ip/index.php
Line: 329
Function: require_once

**Comment by naui95** [comment]
Hi @gklimm thank you for reporting the bug. Could you please confirm that the bug/improvement you are reporting happens in the admin interface (so after login) and not on the online payment page?

**Comment by gklimm** [comment]
![image](https://user-images.githubusercontent.com/1778681/216550176-8ccd3ee8-ce89-453c-91ce-a5ad8aa193ff.png)

**Comment by gklimm** [comment]
By the way, it would certainly make sense to suggest the invoice amount as the default value in the mask?

**Comment by nielsdrost7** [comment]
@gklimm it's merged into development branch and will be added to next (beta) release and in the end, version 1.6.1
