### ISSUE TITLE
ZUGFeRD invalid link redirect

### ISSUE THREAD

**Issue by naui95** [InvoicePlane/InvoicePlane#913]
## Expected Behavior

Activate ZUGFeRD and have the information printed in the PDF. (see IPC post: https://community.invoiceplane.com/t/topic/10099/4?u=naui95)

## Current Behavior

When in Settings/Invoices/PDF Settings - Enabling Include ZUGFeRD will transfer to not valid link → [https://go.invoiceplane.com/zugferdinfo 4](https://go.invoiceplane.com/zugferdinfo)

**Comment by naui95** [comment]
Should redirect to: https://www.ferd-net.de/standards/zugferd/index.html

**Comment by naui95** [comment]
@nielsdrost7 the link is hardcoded in the language file with the key `invoice_pdf_include_zugferd_help` that is in crowdin and I can't edit. Can you change it?

**Comment by gklimm** [comment]
@naui95 I am currently updating to ZUGFeRD 2.2 and will then adjust the link accordingly.

**Comment by nielsdrost7** [comment]
I've changed the Url in the `ip_lang` language file.
Now there are a bunch of other languages that need to be changed as well 🤷‍♂️

**Comment by gklimm** [comment]
Perhaps it makes sense, when I put the actual link into a constant in the module?
