### ISSUE TITLE
$item->product_sku in invoices but not in quotes?

### ISSUE THREAD

**Issue by naui95** [InvoicePlane/InvoicePlane#914]
For the issue see: https://community.invoiceplane.com/t/topic/10126

See fix here: https://github.com/InvoicePlane/InvoicePlane/pull/717 (solution by @ctsde-markus)

To-do
- [ ] test against current release

**Comment by nielsdrost7** [comment]
@ctsde-markus we'll make sure to merge your patch this time

**Comment by naui95** [comment]
Will close the issue since @nielsdrost7 merged. Thanks @ctsde-markus for the fix and the heads up.
