### ISSUE TITLE
Support for PostgreSQL

### ISSUE THREAD

**Issue by ravigupta-art** [InvoicePlane/InvoicePlane#921]
is there a support for PostgreSQL in invoiceplane?
if not, is there a possibility?

**Comment by nielsdrost7** [comment]
We can support it waaaay in the future.
However .... I thought someone made a PR for it.

The things that need to change are:
- the way we connect to the database
- how we insert data (postures doesn't have autoincrementing keys
- maybe some SQL statements as sometimes MySQL is different from PostGres that way

**Comment by ravigupta-art** [comment]
Thanks for the prompt reply.
