### ISSUE TITLE
[Feature Request] In version 1.6 of InvoicePlane the module for online payments with PayPal has been removed due to incompatibilities with the Omnipay package. It would be helpful if it could be put back

### ISSUE THREAD

**Issue by Luca289047** [InvoicePlane/InvoicePlane#934]
Nella versione 1.6 di InvoicePlane è stato rimosso il modulo per i pagamenti online con PayPall.
Sarebbe utile se si potesse rimettere

**Comment by nielsdrost7** [comment]
Translation:
> In version 1.6 of InvoicePlane the module for online payments with PayPal has been removed.
It would be helpful if it could be put back

**Comment by naui95** [comment]
This issue is about PayPal not being included anymore in IPv1. There already is a plan to reintegrate PayPal in IPv1; see: #757 . Closing as a duplicate.
