### ISSUE TITLE
Application blocked (red wheel) when creating an invoice without client

### ISSUE THREAD

**Issue by MoiseRousseau** [InvoicePlane/InvoicePlane#938]
When creating a new invoice, if no client is selected, a message saying the application is blocked is displayed.

## Expected Behavior
A friendly error message telling the user to specify a client

## Current Behavior
A red wheel appear with a default error message ("the application is blocked")

## Screenshots
![Screenshot from 2023-03-12 16-24-55](https://user-images.githubusercontent.com/44249510/224571513-06f74479-9f7f-44ff-8ec5-87780494b6b2.png)

## Possible Solution
A friendly error message telling the user to specify a client

## Steps to Reproduce
With* InvoicePlane v1.6.0
1. Create an invoice from the dashboard
2. Click submit without specifying a client

**Comment by naui95** [comment]
Hi @MoiseRousseau thanks for the bug report. This issue has probably already been addressed by the fix in #927 which is now in the v1.6.1-beta-2 beta run. (see https://github.com/InvoicePlane/InvoicePlane/releases); we will double check that in v1.6.2 this issue is not there anymore. Thank you.

**Comment by kelvin-codes-stuff** [comment]
Added required to the forms in the newest dev build:  v1.6.1-beta-2
