### ISSUE TITLE
Character encoding problem for single quote when chosing Client in new invoice / quote

### ISSUE THREAD

**Issue by MoiseRousseau** [InvoicePlane/InvoicePlane#940]
Characters `'` is not properly displayed in the field Client when creating a new quote or invoice.

For example, client "Bob l'Artisan" is displayed: "Bob l&#09;Artisan".

However, this problem does not occur when opening the client information and clicking "new invoice".

## Expected Behavior
Client name should display correctly

## Current Behavior
Formating problem

## Screenshots
![Screenshot from 2023-03-14 16-37-24](https://user-images.githubusercontent.com/44249510/225131109-7542f274-07fc-4718-b1f9-714c41570cac.png)

## Possible Solution
Probably a formatting problem... `&#09` is the hex representation of the single quote character

## Steps to Reproduce
1. Create a client named "Bob l'Artisan"
2. Go into Dashboard
3. Click Create New Invoice
4. Search Bob in the Client field

## Detailed Description
Using InvoicePlane 1.6.0 configured in French

**Comment by naui95** [comment]
Thank you for the report. This should be also checked out against the new v1.6.1 since some changes in XSS filtering were introduced in the new version. Will have a look at it.

**Comment by kelvin-codes-stuff** [comment]
@MoiseRousseau I solved this issue in #950 :)
