### ISSUE TITLE
[Feature Request] Add BIC code and remittance information fields to user table to simplify bank transfers

### ISSUE THREAD

**Issue by Verony-makesIT** [InvoicePlane/InvoicePlane#942]
## Current Behavior
To make invoice payments, the supplier's bank details are required. 
Currently, this includes the IBAN bank account number which is available in the IP user table. 
Both (**BIC code + remittance information**) fields are currently not available in the IP user table.

## Detailed Description
To make payments (for QR code or bank transfers) **to non-SEPA countries**, the use of the **BIC (SWIFT) code is mandatory**. 
On a (European) bank transfer or QR code you can also include a **remittance information** description or payment reference indicating which invoice you must/want to pay. 

## Possible Implementation
Add BIC code and remittance information fields to the user table: 
- to simplify and set up QR code and bank transfers so that payments for clients in non-SEPA countries can be made more easily. 
- so that invoice payments can be checked more easily (automatically) for the user/supplier.

**Comment by Verony-makesIT** [comment]
The PR is on its way...
For myself, I also set up a "QR code demo" and for this I placed 2 js files (in assets/core/js/) and added a custom public webtemplate (in /invoices_templates/public/) file. 
Check out the result below.
![image](https://github.com/InvoicePlane/InvoicePlane/assets/30659226/dfac0937-dbe3-4da7-967f-539f0703a3d6)
I also prepared "the Remittance info" field to be  (_possibly_) included in the future in a structured format (**using template tags**), so that automatic payment verification can be easily performed by the user/supplier.

**Comment by Verony-makesIT** [comment]
@nielsdrost7, 
I realize that this feature request will no longer be needed when my **PR [IP-939]** is implemented in IP V2.
Shall I remove this PR [IP-942] since it is already a part of the IP-939 functionalities?

**Comment by nielsdrost7** [comment]
Sure, but I think you can only close the PR and the issue.
Same thing, I guess

**Comment by Verony-makesIT** [comment]
Obsolete by PR IP-939.
