### ISSUE TITLE
Feature Request: make custom fields go through trans()

### ISSUE THREAD

**Issue by marneu** [InvoicePlane/InvoicePlane#943]
To make invoices on a broader basis with several languages it would be of help if custom fields  could pass a language translation.
F.e.: _$custom_fields['client']['Konditionen']_ would be ok on a german invoice , on an english customer it would be better printed as 'Conditions' etc.
The translation itself would be ok within _app../language/$LANG/custom_lang.php_

**Comment by nielsdrost7** [comment]
The translation function within InvoicePlane is `_trans()`, so keep that in mind.
If you're making a custom field, let's say `Secondary Address` and of course add it to the database, now you want to translate it: `_trans('`Secondary Address')`, it will be looking in `application/language/english/*.php` for that translation.
If you want to make a Pull-request we're open to that
