### ISSUE TITLE
Captcha / Recaptcha stopping me from submitting/loading invoice

### ISSUE THREAD

**Issue by christoferd** [InvoicePlane/InvoicePlane#947]
Does invoice plane have Captcha / Recaptcha security?

Sometimes I'm unable to load / submit an invoice.
This may be a security issue on the hosting server, trying to figure this out.

**Comment by nielsdrost7** [comment]
> Does invoice plane have Captcha / Recaptcha security?
Which captcha are you talking about?
Can you show a screenshot of the captcha that is stopping you from loading the invoice?
Maybe there is something in the network tab of your browser? (Development tools)

**Comment by kelvin-codes-stuff** [comment]
Hi @christoferd, i want to look into the issue but missing a lot of information. 
Can you provide a screenshot from the issue and a screenshot of the network tab?

**Comment by nielsdrost7** [comment]
Information and steps to reproduce missing. I'm going to close this issue.

@christoferd when you open an issue, there's a template that says 2 things:
- open an issue on the forums
- answer a couple of questions (actually the steps to reproduce)
Now we're missing that info.
