### ISSUE TITLE
Language Files in Crowdin not up to date

### ISSUE THREAD

**Issue by fabm3n** [InvoicePlane/InvoicePlane#951]
## Expected Behavior
The Crowdin project is up-to-date with the current version

## Current Behavior
The Crowdin project is not up-to-date,

## Possible Solution
Update the Crowdin Project

## Steps to Reproduce
Example:
grep -rni "default_notes"
english/ip_lang.php:147:    'default_notes'                                => 'Default Notes',

![image](https://github.com/InvoicePlane/InvoicePlane/assets/11352551/13f0bd74-2ae6-4fc8-b5c0-c8013dc7eb37)

**Comment by nielsdrost7** [comment]
So; what you're saying is that the language files for the English translation on crowdin had some new translations?
Next version (1.6.2) we'll download those files again and will put them in the .zip file

**Comment by fabm3n** [comment]
> So; what you're saying is that the language files for the English translation on crowdin had some new translations? Next version (1.6.1) we'll download those files again and will put them in the .zip file

No, it's the other way around. In GitHub are translations (https://github.com/InvoicePlane/InvoicePlane/blob/development/application/language/english/ip_lang.php#L147) that do not exist in Crowdin.
Downloaded ip.php:
![image](https://github.com/InvoicePlane/InvoicePlane/assets/11352551/e338b6e8-243b-4ec4-8ab2-297626bbd62e)

**Comment by nielsdrost7** [comment]
@fabm3n language files were updated and translated for English

**Comment by fabm3n** [comment]
Thanks @nielsdrost7 !
Will have a look into the translations next week :)
