### ISSUE TITLE
Missing packages on docker arm64

### ISSUE THREAD

**Issue by BhasherBEL** [InvoicePlane/InvoicePlane#952]
## Expected Behavior
On first boot and on pdf generation, some php packages are missing from the arm64 docker image (at least) such as `php7-mbstring`, `php7-json` and `php7-iconv`.

## Current Behavior - Screenshots
![image](https://github.com/InvoicePlane/InvoicePlane/assets/45831883/0f741a4e-c05f-48aa-970d-3acef3c94148)

## Possible Solution
Probably add `apk add php7-iconv php7-mpdf php7-iconv`, but as I don't see any issue related to that, I don't know if it's arm64 related or a most general issue.

## Steps to Reproduce
1. Run this container https://hub.docker.com/r/mhzawadi/invoiceplane#!
2. Try to do the first install or generate a pdf

## Context (Environment)
- arm64
- docker

**Comment by nielsdrost7** [comment]
Post it on his docker github issues list, ok
