### ISSUE TITLE
New Installation Parse Error !! HELPP

### ISSUE THREAD

**Issue by iyovi** [InvoicePlane/InvoicePlane#958]
[09-Jul-2023 10:38:53 UTC] PHP Fatal error:  Uncaught Dotenv\Exception\InvalidFileException: Failed to parse dotenv file. Encountered an invalid name at [<?php exit('No direct script access allowed'); ?>]. in /home/folder/mydomain.com/vendor/vlucas/phpdotenv/src/Parser/Parser.php:30
Stack trace:
#0 /home/folder/mydomain.com/vendor/graham-campbell/result-type/src/Error.php(118): Dotenv\Parser\Parser::Dotenv\Parser\{closure}()
#1 /home/folder/mydomain.com/vendor/vlucas/phpdotenv/src/Parser/Parser.php(31): GrahamCampbell\ResultType\Error->mapError()
#2 /home/folder/mydomain.com/vendor/vlucas/phpdotenv/src/Dotenv.php(222): Dotenv\Parser\Parser->parse()
#3 /home/folder/mydomain.com/index.php(20): Dotenv\Dotenv->load()
#4 {main}
  thrown in /home/folder/mydomain.com/vendor/vlucas/phpdotenv/src/Parser/Parser.php on line 30

PHP Version 8.1. It also falls directly to 500 errors. I shared the content of the error_log file with you. Can you help me?

**Comment by kelvin-codes-stuff** [comment]
Hi, would you move it to our community forum?Github issues are more for bugs. https://community.invoiceplane.com

**Comment by iyovi** [comment]
> Hi, would you move it to our community forum?Github issues are more for bugs. I think this is another issue. https://community.invoiceplane.com

Thanks for the forum I created the subject in the status of the process.

**Comment by nielsdrost7** [comment]
For everyone else coming here from google:
This is the documentation regarding updating / upgrading InvoicePlane:
https://wiki.invoiceplane.com/en/1.6/getting-started/updating-ip

Basically, the steps are as follows:

- open `ipconfig.php` and **comment out the top line in the file by adding a # _(and a space!)_ at the beginning of the first line**. The result should be like this:
- `# <?php exit('No direct script access allowed'); ?>`
- close the ipconfig.php file
