### ISSUE TITLE
Incorrect Swedish translation of 'Subtotal'

### ISSUE THREAD

**Issue by biosocket** [InvoicePlane/InvoicePlane#966]
## Expected Behavior
"Subtotal" should be translated to "Exkl. moms" in the Swedish translation files.

## Current Behavior
"Subtotal" is translated to "Totalt" which is the same as total.

## Steps to Reproduce
1. Create a Swedish invoice.
2. Look at the invoice. It's confusing because total appears twice.

**Comment by nielsdrost7** [comment]
@biosocket take a look and see if you can make more improvements to the translations:
https://crowdin.com/translate/fusioninvoice/1/en-sv?filter=basic&value=0#q=Subtotal

**Comment by nielsdrost7** [comment]
@biosocket did you manage to make that change in the translations?
I'll close this issue for now
