### ISSUE TITLE
Custom Fields Not Working As Intended

### ISSUE THREAD

**Issue by YasirRWebDesigner** [InvoicePlane/InvoicePlane#979]
## Expected Behavior
After adding a `$custome_field` to the invoice template should show the field data in the invoice.

## Current Behavior
PHP Error Message: Undefined array key "client_code"

## Screenshots
![image](https://github.com/InvoicePlane/InvoicePlane/assets/32537564/6e49ecb1-4e97-4142-bff9-55ddb8f542be)

## Steps to Reproduce
1. Add a custom field to the client.
2. Assume the array for the custom field that you added.
3. Add the code to the invoice template

## Context (Environment)
We need a couple of fields that we need in the invoice like, Lead Source, Client ID/Code, Place of Practice(Hospital/Clinic Name), and a few others but I can't get the custom fields to show in the invoice template.

## Detailed Description
As far as I know, I don't think I am doing any wrong here and the Docs are outdated or something idk, I have no idea what's going on here. First of all in the Docs, the custom fields section is shown like this.
![image](https://github.com/InvoicePlane/InvoicePlane/assets/32537564/03984269-f908-434c-9f30-fd119502eb2b)
Now in this screenshot, we can see the columns table and I think this is the array key but I see something like this 
![image](https://github.com/InvoicePlane/InvoicePlane/assets/32537564/0ddea937-8997-4f4a-aa71-47d0d4ef6875)
This is the code I added to the invoice template `<?php echo $custom_fields['client_code'] ?>`I did manage to customize the layout pretty easily but the custom fields are something I am not able to get a grip on. Now I think I did everything right but idk...

![image](https://github.com/InvoicePlane/InvoicePlane/assets/32537564/f5748a64-8d5e-4555-ae55-806a0cce803a)

**Comment by YasirRWebDesigner** [comment]
nvm I am an Idiot 

`<?php echo $custom_fields['client']['CRM ID'] ?>`

I needed to define where the custom field was `[client]` or `[invoice]`

**Comment by nielsdrost7** [comment]
Thanks for updating your issue, man! Glad it was something simple

**Comment by YasirRWebDesigner** [comment]
me too, took 2 hours to see what I was doing wrong lol.
