### ISSUE TITLE
Custom Field need to refilled after save

### ISSUE THREAD

**Issue by YasirRWebDesigner** [InvoicePlane/InvoicePlane#980]
Facing this issue on the Invoices Page, I have a few custom fields on that page, but sometimes if you fill the custom fields after clicking the save button some of the fields return empty.

## Expected Behavior
The text should stay in the custom fields after the page reloads.

## Current Behavior
sometimes some or all the field data gets removed/erased.

## Screenshots
![3](https://github.com/InvoicePlane/InvoicePlane/assets/32537564/6b564d11-5021-4f5a-9b42-4988f7529ab1)

## Steps to Reproduce
1. Add Custom Fields to Invoices
2. Open an existing invoice(I didn't test it on a new invoice).
3. Fill in the custom fields and click save. (wait for the page to reload)

## Context (Environment)
Every time I have to fill in custom fields multiple times before I could send the invoice.

## Detailed Description
Hi, It's me again, So I am facing this issue on the Invoices Page, I have a few custom fields on that page, but sometimes if you fill in the custom fields after clicking the save button some of the fields return empty. The data you fill in gets removed/erased but some don't save anything sometimes it even removes the data that was already in a field. Like in the image below, I added the data and the IBAN data wasn't there after the page reloaded. 

## Off-Topic
There's one more thing I wanna share the custom invoice layout I made with you guys, The current ones are annoying & confusing plus the layouts do not match. I still need to do some work but the layout will look like this for all the templates. 
![final_page-0001](https://github.com/InvoicePlane/InvoicePlane/assets/32537564/f4dda9fa-8c7f-460d-8642-aad4ae51162f)

I edited the image to show what I did.
![layout_page-0001](https://github.com/InvoicePlane/InvoicePlane/assets/32537564/ef839264-54d0-4020-991d-582d76714bae)
I have a few minor things to do like removing those custom fields. I added. I'll submit the layouts soon.

**Comment by nielsdrost7** [comment]
> I have a few minor things to do like removing those custom fields. I added. I'll submit the layouts soon.

O, wow, that looks awesome! In this case I'll wait with releasing a final 1.6.1 version (beta-3 is this weekend)

**Comment by YasirRWebDesigner** [comment]
> > I have a few minor things to do like removing those custom fields. I added. I'll submit the layouts soon.
> 
> O, wow, that looks awesome! In this case I'll wait with releasing a final 1.6.1 version (beta-3 is this weekend)
> 
> Would you like to join our Slack chat? I have some interesting challenges we need your help with

Sure I will, btw only know HTML/CSS/JS idk PHP, I just understand it a little bit but I'll do my best.

**Comment by nielsdrost7** [comment]
I Wasn't able to reproduce the bug, added more logging. Next time this happens, check the application/log file, because I added a log entry with the number "980", to specify this bug report
