### ISSUE TITLE
Add trim to client search

### ISSUE THREAD

**Issue by rycardo74** [InvoicePlane/InvoicePlane#992]
## Expected Behavior

Filter space on the client name when copy and paste!

## Current Behavior

when a space is in front of a Client name the filter doesn't work

## Screenshots

![image](https://github.com/InvoicePlane/InvoicePlane/assets/53749578/452704fa-2452-4c9f-924b-d73e87612771)

## Possible Solution

application/modules/filter/controllers/Ajax.php
add trim on line 73
$keyword = trim(strtolower($keyword));

## Steps to Reproduce

1.
2.
3.
4.

**Comment by nielsdrost7** [comment]
resolved in development branch, will come with next release (1.6.1 final)

**Comment by nielsdrost7** [comment]
@rycardo74 version 1.6.1 was released just a few minutes ago: https://github.com/InvoicePlane/InvoicePlane/releases/tag/v1.6.1, I'm closing the issue
