### ISSUE TITLE
HTML Email Templates cannot be used

### ISSUE THREAD

**Issue by reisi007** [InvoicePlane/InvoicePlane#994]
## Expected Behavior
I save a long email template and I can use it later (I am using 1.6.0)

## Current Behavior
It seems to me that not the whole text gets copied, email however is broken, copy pasing email template works

## Screenshots
E Mail template page
![E Mail template](https://github.com/InvoicePlane/InvoicePlane/assets/2719454/cf7c3a00-92b1-4277-8619-1e2c52357cdb)

Send email page
![Send email page](https://github.com/InvoicePlane/InvoicePlane/assets/2719454/7768a38e-4836-4ecf-b213-d7fadcf408be)

## Possible Solution

Seems to me that inserting the text into the texbox is a problem

## Steps to Reproduce

1. Get a html email ( https://app.postdrop.io/ -> download/export the default template)
2. Save it as e.g invoice template on InvoicePlane ( see dirst screenshot above)
3. Try sending a mail, message textbox gets populated incorrectly
4. (Workaround); manually copy & paste the email template. Storing and receiving in email template section seem to work, fine so the information should be there

## Context (Environment)

I am trying to send HTML emails. I cannot really use the email template feature as I cannot restore / apply the template when sending invoices

It seems to me that inserting the text into the send invoicec feature does not work as expected. It feels like HTML gets pasted and not the text

## Detailed Description

I would like that if I select a email template it works like I would copy&paste the content

## Possible Implementation

I have not looked through the code, but instead of setting the innerHtml of the textbox setting the innerText? Maybe I am lucky and that is the fix :p 

## Failure Logs
<!-- Please include any relevant log snippets or files here.
Not attaching a log as no error is generated

**Comment by nielsdrost7** [comment]
Hi there,
I like the issue, but
Would you mind just pasting the parts _between_ <body> and </body> in that html template?
InvoicePlane will add the <html> and <body> tags

So if you get your template from that Url it would be:
```
<table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
...
</table>
```
I don't know about adding the css separately, but try to add that <table> through </table> first and see if that resolved your problem.

With **version 2** of InvoicePlane, we'll re-visit pasting an entire html template.

**Comment by nielsdrost7** [comment]
> I have not looked through the code, but instead of setting the innerHtml of the textbox setting the innerText? Maybe I am lucky and that is the fix
we'll also look into that one, thanks for the hint

**Comment by reisi007** [comment]
Hi @nielsdrost7 ,

Your suggestion seems to work, If I paste everything when sending email it seems to work fine, will be changing my template
