### ISSUE TITLE
Product search included!

### ISSUE THREAD

**Issue by eshad** [InvoicePlane/InvoicePlane#996]
## Screenshots

<img width="1198" alt="Screenshot 2023-11-01 at 4 18 18 PM" src="https://github.com/InvoicePlane/InvoicePlane/assets/4688406/5ae2a17b-85d9-418a-96c3-27149a764539">

**Comment by clockwiseq** [comment]
@eshad, could you provide more details please?

**Comment by nielsdrost7** [comment]
@eshad I'm going to close the issue.
The best place to ask your questions is the forums:
https://community.invoiceplane.com

Once has been established, that you have a real issue, you're free to open another issue on the issues list
